### PR TITLE
Use a LaTeX parser

### PR DESCRIPTION
**Pull request by tamuratak**
I have written a [LaTeX parser](https://github.com/tamuratak/latex-utensils) based on [LaTeX.js](https://github.com/michael-brade/LaTeX.js) and [latex-parser](https://github.com/siefkenj/latex-parser) using [peg.js](https://github.com/pegjs/pegjs). It must be useful for LaTeX Workshop.

As the first step, let's use it to extract commands defined with multi lines in the preamble. Related to #1428.

スクリーンショット 2019-07-13 0 57 28

### CODE REVIEW

**Comment by tecosaur** [comment]
Nice! I could also do with this for getting stuff like `\tikzset` contents in #1500

**Comment by tamuratak** [comment]
@James-Yu @jlelong if no objection, I want to merge this PR.

**Comment by jlelong** [comment]
No objection but I have a few questions to better understand the motivation behind this change. I am probably already labelled as the _maintenance_ guy, so I am not afraid of saying to I am mainly concerned with maintainability in this change.
- What is the gain in terms of robustness for LaTeX-Workshop? I have the feeling you can parse `\newcommand` definitions split over several lines. Do you confirm that?
- What is the maturity of `latex-utensils`? 
- You are the only maintainer so all the pressure is on you. Do you fell we could rely more on `latex-utensils` for other things in LaTeX-Workshop?

**Comment by tamuratak** [comment]
> What is the gain in terms of robustness for LaTeX-Workshop? I have the feeling you can parse \newcommand definitions split over several lines. Do you confirm that?

Yes. With latex-utensils, we can reduce the number of codes of parsing with regex. They easily lead to bugs and make maintenance difficult.

> What is the maturity of latex-utensils?

I think it is matured. At least for this PR. 

> Do you fell we could rely more on latex-utensils for other things in LaTeX-Workshop?

It is the motivation why I have developed latex-utensils. However, the scope of application would be limited because a LaTeX document being edited is often not grammatically correct and cannot be parsed without errors. A typical usage would be extracting a part of the document and paring it with latex-utensils.

---

The parser is generated by PEG.js from a file `latex.pegjs`. For example, LaTeX environment is defined as follows:

```js
Environment
  = beginEnv name:groupedEnvname args:(argumentList / Group)*
      skip_space body:(!(endEnv n:groupedEnvname & {return name === n;}) x:Element {return x;})*
    endEnv groupedEnvname
  {
    return { kind: "env", name, args, content: body, location: location() };
  }
```

**Comment by tamuratak** [comment]
We can see AST (abstract syntax tree) returned by latex-utensils as follows:
```
$ cat sample/t.tex         
\documentclass[12pt]{article}
\begin{document}
  abcd
\end{document}
                       
$  ./node_modules/.bin/luparse -i --color sample/t.tex
{ kind: 'ast.root',
  content:
   [ { kind: 'command',
       name: 'documentclass',
       args:
        [ { kind: 'arg.optional',
            content: [ { kind: 'text.string', content: '12pt' } ] },
          { kind: 'arg.group',
            content: [ { kind: 'text.string', content: 'article' } ] } ] },
     { kind: 'env',
       name: 'document',
       args: [],
       content:
        [ { kind: 'text.string', content: 'abcd' },
          { kind: 'parbreak' } ] } ],
  comment: undefined }
```

**Comment by jlelong** [comment]
I guess this is time for merging.

**Comment by James-Yu** [comment]
Really looking forward to more robust syntax parsing by this parser!

**Pull request merged**
