### PR TITLE
Format all the things

### PR DESCRIPTION
**Pull request by tecosaur**
The formatting in this project seems a tad inconsistent.

So, for your perusal here's a PR which is the result of running ~300 files in this project through tslint + prettier. Quite a few of the modified json files just have an extra newline at the end.

Formatting config:
 - Max line length: 120
 - spaces per indent: 4 (ts), and 2 (json)

All other settings are defaults / using this project's tslint.

**I don't expect this to be merged, but do let me know what you think.**

They're also some tslint rules that can be set to help set a more consistent coding style. I've added these rules.

 - [no-null-keyword](https://palantir.github.io/tslint/rules/no-null-keyword/)
 - [no-return-await](https://palantir.github.io/tslint/rules/no-return-await/)
 - [no-string-literal](https://palantir.github.io/tslint/rules/no-string-literal/)
 - [no-string-throw](https://palantir.github.io/tslint/rules/no-string-throw/)
 - [prefer-object-spread](https://palantir.github.io/tslint/rules/prefer-object-spread/)
 - [static-this](https://palantir.github.io/tslint/rules/static-this/)
 - [arrow-return-shorthand](https://palantir.github.io/tslint/rules/arrow-return-shorthand/)
 - [interface-over-type-literal](https://palantir.github.io/tslint/rules/interface-over-type-literal/)
 - [no-boolean-literal-compare](https://palantir.github.io/tslint/rules/no-boolean-literal-compare/)
 - [no-unnecessary-qualifier](https://palantir.github.io/tslint/rules/no-unnecessary-qualifier/)
 - [object-literal-key-quotes](https://palantir.github.io/tslint/rules/object-literal-key-quotes/)
 - [ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/)
 - [prefer-method-signature](https://palantir.github.io/tslint/rules/prefer-method-signature/)
 - [prefer-while](https://palantir.github.io/tslint/rules/prefer-while/)
 - [space-before-function-paren](https://palantir.github.io/tslint/rules/space-before-function-paren/)
 - [space-within-parens](https://palantir.github.io/tslint/rules/space-within-parens/)
 - [arrow-parens](https://palantir.github.io/tslint/rules/arrow-parens/)
 - [linebreak-style](https://palantir.github.io/tslint/rules/linebreak-style/)
 - [newline-before-return](https://palantir.github.io/tslint/rules/newline-before-return/)
 - [number-literal-format](https://palantir.github.io/tslint/rules/number-literal-format/)
 - [trailing-comma](https://palantir.github.io/tslint/rules/trailing-comma/)

I picked these because they all have fixers, and so can be applied without any extra effort from contributors.

### CODE REVIEW

**Comment by jlelong** [comment]
Very good initiative but we have to be very careful before merging this as it makes file history more difficult to use. A few thoughts

1. We should make a new release before merging
1. I would rather have `.then` construction on the same line as the closing `)`of the promise
1. No space before `(` in functions definition
1. No space inside `()`, but space inside `{}`
1. Breaking long lines does not always improve readability especially in [main.tex](https://github.com/James-Yu/LaTeX-Workshop/blob/73e75683908356205df597c699765f413612e9ce/src/main.ts)

I will think of all this again and may come up with more comments. I guess discussion is welcome.
@James-Yu your opinion?

**Comment by tecosaur** [comment]
Thanks @jlelong. To clarify my intent with this is mostly just to start a discussion — not so much to have this particular set of rules merged.

**Comment by tecosaur** [comment]
Oh, and @jlelong in response to those points

1. Ok
2. Not sure how that can be done as a rule
3. If you can say which of these you a space before, then that's easy to fix
   - anonymous functions
   - named functions
   - async arrow functions
   - class methods
   - class constructors
4. I've set `space-within-parens` to be false, where's the undesired () space appearing?
5. I imagine that will have to be manually fixed

Also, I think it would be good to try to minimise the amount of changes at the end of this, so I think at the end if we work out a set of styling rules that we're happy with I'll close this PR and open a new one which just goes from current master state to final agreed state.

**Comment by jlelong** [comment]
@tecosaur 

1.
1. Maybe we can play a bit with `ignoreChainWithDepth` and `newline-per-chained-call`
1.  For sure named functions and class methods and constructors
1. You are right, everything is fine
1. This could be achieved with 
    ````
    /* eslint-disable max-len */
      Some code
    /* eslint-enable max-len */
    ````

Let us just keep working out a satisfying and little intrusive style.

**Comment by tecosaur** [comment]
Just to clarify with *3.* Are those the types you **do** or **don't** want a space before the `(`?

**Comment by jlelong** [comment]
In _3._, these are those I do not want space before `(`.

**Comment by jlelong** [comment]
I will come back to this PR once #1496 is merged.

**Comment by tecosaur** [comment]
@jlelong *cough

**Comment by jlelong** [comment]
@tecosaur this is still in my todo list but time is missing. Is the `tslint.json` file up-to-date with the last changes we discussed? If so, I will run `tslint` myself and have a look at the result.
Small side remark: stuff in `data/packages/` should not be reformatted because it is automatically generated from scripts in `dev/`.

**Comment by tamuratak** [comment]
Notice that tslint will be deprecated in 2019. See palantir/tslint/issues/4534.

**Comment by tecosaur** [comment]
I'm aware. However they also apparently plan on releasing a conversion tool, so I don't think we need to do anything other then use the tool when it's released.

**Comment by tecosaur** [comment]
@jlelong I haven't been able to resolve
> `2`. I would rather have .then construction on the same line as the closing )of the promise
> `5`. Breaking long lines does not always improve readability especially in main.ts

However other than that it should be good.

**Comment by tamuratak** [comment]
@tecosaur I don't think so. We should start to use eslint now rather than adding more rules to `tslint.json` since the completeness of the migration tool is unknown.

**Comment by tecosaur** [comment]
@tamuratak I know that the typescript team were/are trying to integrate all the features of typescript into eslint? Do you know how far along they are? i.e. whether it's in a state where it works as a replacement yet?

**Comment by tamuratak** [comment]
See https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md

**Comment by tamuratak** [comment]
You can try eslint in this [branch](https://github.com/tamuratak/LaTeX-Workshop/tree/use_eslint). Since the CLI of eslint does not have an option `--project`, we have specify ts files.

```sh
npm install --save-dev
./node_modules/.bin/eslint src/main.ts

/Users/tamura/src/github/LaTeX-Workshop/src/main.ts
   64:143  warning  Unexpected any. Specify a different type    @typescript-eslint/no-explicit-any
  186:27   error    'Extension' was used before it was defined  @typescript-eslint/no-use-before-define

✖ 2 problems (1 error, 1 warning)

```

**Comment by tamuratak** [comment]
Updated the [branch](https://github.com/tamuratak/LaTeX-Workshop/tree/use_eslint). 

It seems that eslint will not provide all the features tslint provides even after tslint deprecated.  The migration tool cannot be complete. This PR only increases works we have to do when we migrate to eslint. We should close this PR and have to discuss the migration to eslint instead.

@tecosaur it is not honest not to mention it in the description of this PR while being aware that tslint will be deprecated.

**Comment by jlelong** [comment]
I am closing this PR as it is now clear that we should forget `tslint` and directly try to use `eslint`.
@tamuratak Are you already happy with your `eslintrc.json`? I will try it when I have time.

**Comment by tamuratak** [comment]
The main incompatibility of tslint and eslint for us is that [typedef-whitespace](https://palantir.github.io/tslint/rules/typedef-whitespace/). We enforce different styles for the colon of the argument type and the one of the return type. `no space : one space` and `one space : one space`. eslint does not allow such a configuration.

```typescript
function f(a: ArgType) : ReturnType {
   ...
}
```

We also have to decide whether we use [Prettier](https://prettier.io/) as an alternative to the [whitespace](https://palantir.github.io/tslint/rules/whitespace/) rule.

**Comment by jlelong** [comment]
This is no so much an issue. I guess we could use `no space : one space`.

**Pull request closed without merging**
