### PR TITLE
Add \addplot grammar support

### LINKED ISSUE #1963: Gnuplot support for pgfplots
**Is your feature request related to a problem? Please describe.**

Would it be possible to fix syntax colouring when using gnuplot with pgfplots ? Since we can use the dollar sign to call columns, it breaks the syntax colouring of the whole document (see screenshot below).

**Describe the solution you'd like**
It seems that gnuplot syntax colouring is already supported for `gnuplot` environnement (see #916) 

**Describe alternatives you've considered**

At least disable syntax colouring in the example case so that it does not break the whole document.

**Additional context**
image

### PR DESCRIPTION
**Pull request by jlelong**
Fix #1963

### CODE REVIEW

**Comment by jlelong** [comment]
@PierreMarchand20 Could you test this branch and let me know if the regex is robust enough
https://github.com/James-Yu/LaTeX-Workshop/blob/dc3da70ca43d3320a29de1909d23c17f575e0ec3/syntax/LaTeX.tmLanguage.json#L503

**Comment by PierreMarchand20** [comment]
Sure, could you just remind me how to use this extension locally ? So far, I have cloned the repository, I did `npm install` in the folder of the repository and then I launched the debugger. But then the local version is not picked up, did I miss something ?

**Comment by jlelong** [comment]
You just need to run

```bash
git clone https://github.com/James-Yu/LaTeX-Workshop.git
cd ./LaTeX-Workshop
git checkout 1963-pgfplots-support
npm install --no-optional
code .
```

Then, launch the debugger. It will run the local version

**Comment by PierreMarchand20** [comment]
Ok then, the example I gave does not work: 
image
How can I check that I am using the local version ?

**Comment by jlelong** [comment]
Strange because obviously your example works. In `LaTeX-Workshop`, make sure you are on the correct branch `1963-pgfplots-support`, then running `code -n .` should open a new VSCode window. Launching the debugger will fire up a `Extension Development Host` window, in which you have to open the `.tex` you want to check.

**Comment by PierreMarchand20** [comment]
I am on the right branch 
image
I have the repo in a new window on the right branch 
image
I run it 
image

But I get the picture I sent you previously. But the very first time I tried to debug, I got an error message about something missing and that it was not able to launch the local version of the extension. But I cannot reproduce it now...

**Comment by PierreMarchand20** [comment]
I deleted the folder and reinstall everything as you said, but same remarks as my previous message.

**Comment by PierreMarchand20** [comment]
Here's the development tool:
image

**Comment by jlelong** [comment]
> I got an error message about something missing and that it was not able to launch the local version of the extension

That may be the issue. Can you run `npm run compile` directly in the extension repository?

**Comment by PierreMarchand20** [comment]
Ok, I did and I got 
```
❯ npm run compile

> latex-workshop@8.7.2 compile /Users/pfcm20/Partage/vscode/LaTeX-Workshop
> tsc -p tsconfig.json && tsc -p viewer/tsconfig.json
```
but then it did not change anything. But according to the development tool it seems that the local version is indeed loaded no ?

**Comment by PierreMarchand20** [comment]
So I checked that I am using the local version (I modified a scope for the `pycode` environment and checked the scope was changed while debugging), and my example does not work.

**Comment by PierreMarchand20** [comment]
I noticed that if I do not have any extension providing `source.gnuplot`, then it breaks. But if I have such an extension, it works fine, here's a more complicated example:
image

But there is something I do not understand following #916 and that you can see in my example. We use the syntax colouring of gnuplot, but the way we need to comment is like latex, so they are not grey as one would expect. So I do not understand what kiryph says in #916 because for me, commenting the python/gnuplot way breaks compilation...

**Comment by jlelong** [comment]
For sure, you need an other extension to provide gnuplot support. I have tries with https://marketplace.visualstudio.com/items?itemName=mammothb.gnuplot I confirm that commenting uses `#` inside `\addplot`. 

> So I do not understand what kiryph says in #916 because for me, commenting the python/gnuplot way breaks compilation...

That is a problem because then the content of `\addplot` is not true gnuplot style. I will try to improve it later today.

**Comment by PierreMarchand20** [comment]
1) What surprised me is that if you do not have a gnuplot extension, the colouring breaks. I would expect that the latex colouring works and that there is no colouring at all for the gnuplot script without gnuplot extension, this is not the case. But why not.

2) The issue about comments I was mentioning is that it takes the gnuplot comment style (using `#`) but it does not compile. It is an issue of `pgfplots`, not of this extension. For example, in a `\begin{gnuplot}...\end{gnuplot}`, it comments automatically with `#` and it compiles because the related package `gnuplottex` provides this functionality. I submitted a feature request to `pgfplots` about it: https://sourceforge.net/p/pgfplots/support-requests/23/

**Comment by PierreMarchand20** [comment]
Thank you for the PR and the quick answer by the way!

**Comment by jlelong** [comment]
1. If you do not have a gnuplot extension, the gnuplot language is unknown and the embedding does not work (`source.gnuplot` is unknown)
1. If we consider the `%` comment approach is a bug from `pgfplots`, there are two options
    1. We use the full embedding, meaning that commenting will not work as it will use `#`. We hope it will be fixed soon by the `pgfplots` guys
    1. We only use gnuplot syntax highlighting and on top of it I declare anything after % as a comment. At least I try. Everything will be fully working, but we will have to come to it later when `pgfplots` is fixed.

   May feeling is that ii. would be better.

**Comment by PierreMarchand20** [comment]
1) strange default behaviour of vscode but ok. 

2) Sure ii) would be better in the meantime, if you can do it. It was just to say that if you do not it would be understandable ^^

**Comment by jlelong** [comment]
I have just implemented ii. Can you give it a try and let me know?

**Comment by PierreMarchand20** [comment]
It works fine, thank you !

**Comment by jlelong** [comment]
So I am merging it. Let me know if/when commenting with `#` is supported.

**Comment by PierreMarchand20** [comment]
FYI: pgf-tikz/pgfplots#346

**Pull request merged**
