### PR TITLE
make arguments for latexindent configurable

### PR DESCRIPTION
**Pull request by project-pp**
Hello, I'm using LaTeX-Workshop everyday!! 
I wrote new option ”latex-workshop.latexindent.args”, which make arguments for latexindent configurable. I think it is minor problem but it would improve this extension.
regards,

### CODE REVIEW

**Comment by James-Yu** [comment]
Thanks for your contribution. It will absolutely improve the extension.

In the meantime, can you please modify it to obey the common `args` pattern for other tools, i.e., list of string instead of a plain string? This is more a consistency consideration. In addition, `latexindent` should be `spawn`-ed instead of `exec`-ed by `child_process`, on which I will work later (PR appreciated!).

**Comment by project-pp** [comment]
I agree, it mus be `string[]`, but how is the `stdio` option of `spwan`?
I mean, at this moment `latexformatter.ts` ignores stderr, I thought it would be better to handle and post it via `addLogMessage`.

**Comment by project-pp** [comment]
I agree, it should be `string[]`.
The next commit implements both stdout and stderr handler.
It seems to work for me:smile:

**Comment by project-pp** [comment]
Note for about 966ee31:
At this moment `-c` option of `latexindent ` requires a path with trailing slash.
c.f. https://github.com/cmhughes/latexindent.pl/blob/2cf5ae5cb57017fe383ebe1a8420f95abb63f95c/LatexIndent/LogFile.pm#L97
I just add it to `latex-workshop.latexindent.args` (so anyone can remove when it is no longer needed).

**Comment by James-Yu** [comment]
Nice job! One last request: can you please add a brief description to `%TMPFILE%` and `%INDENT%` to the description of the config item? They are nowhere else defined.

**Comment by project-pp** [comment]
Exactly.
I think it would be better to add information about `latex-workshop.latexindent.*` into README (but i'm not good at english...pls can you or can anyone later...?:innocent:)

**Comment by James-Yu** [comment]
Nor am I a native speaker but I'd like to try. Thank you again for your contribution!

**Pull request merged**
