### PR TITLE
Update pdfjs to 2.2.228

### PR DESCRIPTION
**Pull request by tamuratak**
Update pdfjs to 2.2.228.

### CODE REVIEW

**Comment by trevorgunn** [comment]
I'm having issues with this on Windows (it works fine on Linux). The PDF is blank and the data type `loaded` is never sent. This is the developer console:

```
[Embedded Page] Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
webviewElement.ts:303
[Embedded Page] Uncaught (in promise) TypeError: pdfDocument.getPageLayout is not a function webviewElement.ts:303
```

This is what the logger says:

```
[21:10:35] Initializing LaTeX Workshop.
[21:10:35] pdflatex is provided by MiKTeX
[21:10:35] Creating LaTeX Workshop http and websocket server.
[21:10:35] LaTeX Workshop initialized.
[21:10:38] Found root file from active editor: c:\Users\Trevor\Documents\Latex Test File\main.tex
[21:10:38] Root file changed from: undefined to c:\Users\Trevor\Documents\Latex Test File\main.tex. Find all dependencies.
[21:10:38] Instantiating a new file watcher for c:\Users\Trevor\Documents\Latex Test File\main.tex
[21:10:38] Creating file watcher for .bib files.
[21:10:38] Parsing c:\Users\Trevor\Documents\Latex Test File\main.tex
[21:10:38] Server created on 127.0.0.1:49181
[21:10:38] Adding c:\Users\Trevor\Documents\Latex Test File\main.tex to file watcher.
[21:10:38] Snippet data loaded.
[21:10:38] LaTeX Workshop version: 8.2.0
[21:10:45] VIEW command invoked.
[21:10:45] Found root file from active editor: c:\Users\Trevor\Documents\Latex Test File\main.tex
[21:10:45] Root file remains unchanged from: c:\Users\Trevor\Documents\Latex Test File\main.tex.
[21:10:45] Serving PDF file at http://localhost:49181/viewer.html?file=pdf..YyUzQSU1Q1VzZXJzJTVDVHJldm9yJTVDRG9jdW1lbnRzJTVDTGF0ZXglMjBUZXN0JTIwRmlsZSU1Q21haW4ucGRm
[21:10:45] The encoded path is c:\Users\Trevor\Documents\Latex Test File\main.pdf
[21:10:45] Open PDF tab for c:\Users\Trevor\Documents\Latex Test File\main.pdf
[21:10:46] Found root file from active editor: c:\Users\Trevor\Documents\Latex Test File\main.tex
[21:10:46] Root file remains unchanged from: c:\Users\Trevor\Documents\Latex Test File\main.tex.
[21:10:47] Handle data type: open
[21:10:47] Preview PDF file: c:\Users\Trevor\Documents\Latex Test File\main.pdf
```

**Comment by tamuratak** [comment]
Please provide all the information required in the issue template.

**Comment by trevorgunn** [comment]
Sorry:

OS is Windows 10.0.18362
Latest commit I tested is c07ebfd28e2dae5f7b79415123456427756a1bbf
VSCode is version 1.39.2

Not using VSCode remote at all.

**Comment by tamuratak** [comment]
I can not reproduce:

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Windows 10 Home 1809

**Comment by tamuratak** [comment]
Anyway, please open a new issue.

**Pull request merged**
