### PR TITLE
Refactor glossary intellisense data scanning

### LINKED ISSUE #3280: Glossary intellisense broken when label contains '_'
Intellisense for glossaries does not work correctly when the glossaries label has a " _ " symbol. What follows " _ " simply does not appear. 

Here is an example:

gloss_def
vscode

It seems that it does not show what follows " _ ", but nevertheless shows the description "E _ P", although later in the construction, the acronym of {E} (Elastic Modulus) appears.

_Originally posted by @AguirreNicolas in https://github.com/James-Yu/LaTeX-Workshop/issues/2783#issuecomment-1116193391_

### PR DESCRIPTION
**Pull request by jlelong**
This PR refactors the scanning par t of `Glossary` class.

- Stop directly accessing `node.kind`. Instead use the `latexParser.isXXX` methods.
- Use `stringify` to recompute labels and descriptions. Close #3280

### CODE REVIEW

**Comment by tamuratak** [comment]
Since it is difficult to review `glossary.ts`, I leave a general comment.

In the following part, it is not a good practice to access `node.args[0]` directly without a null check. If you check it is not null somewhere else, you should state it with the type system. In other words, `getLongNodeLabelDescription` should take something like `{ arg0GoodName: ..., arg1GoodName: ..., arg2GoodName: ..., arg3GoodName: ... }` as an argument, not `latexParser.Command`.

https://github.com/James-Yu/LaTeX-Workshop/blob/b079d377863cb6bbc1e589b99f1004e916420b04/src/providers/completer/glossary.ts#L106-L122

I can say the same thing about `getShortNodeDescription`:

https://github.com/James-Yu/LaTeX-Workshop/blob/b079d377863cb6bbc1e589b99f1004e916420b04/src/providers/completer/glossary.ts#L138-L147

**Review by tamuratak — APPROVED** [review]

**Comment by jlelong** [comment]
@tamuratak Thanks for the comments. Now, I check if the number of arguments for the different commands is correct. If not, the entry is dropped.

**Comment by jlelong** [comment]
@tamuratak I am trying to execute some CI tests inside VS Code for debugging. Do you have any idea why they all fail on a rejected promise waiting for `findrootfileend`?

```
1) Completion test suite
       fixture003: @-snippet completion with trigger #:
     Error: promisify (findrootfileend): Timeout error
      at Timeout._onTimeout (/Users/jl/devel/LaTeX-Workshop/test/utils/ciutils.ts:192:26)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

node_modules/mocha/lib/reporters/base.js:305
Error: 1 tests failed.
    at /Users/jl/devel/LaTeX-Workshop/test/completion.index.ts:27:32
    at done (/Users/jl/devel/LaTeX-Workshop/node_modules/mocha/lib/mocha.js:1058:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by tamuratak** [comment]
How about increasing the number?

https://github.com/James-Yu/LaTeX-Workshop/blob/d93e78a22e3dbe7d4d12e29ee9aea8f932ba1fcf/test/utils/ciutils.ts#L193

**Comment by tamuratak** [comment]
I will add a tweak to `ciutils.ts`

**Comment by tamuratak** [comment]
I have added fad5410b3d2395a1843a1d51399df1a16356e121

**Comment by jlelong** [comment]
Thanks! Everything works fine now.

**Pull request merged**
