### PR TITLE
`unified-latex`-based LaTeX and DocTeX structuring

### PR DESCRIPTION
**Pull request by James-Yu**
This PR is a follow-up of the discussion in #3877 and a first attempt of migrating to `unified-latex`.

The logic of constructing structure is almost retained, with only proper adaptation to `unified-latex`.

This PR also serves a demo on how `unified-latex` can be integrated into this extension.

### CODE REVIEW

**Comment by James-Yu** [comment]
NB: The refactor passes previous structure tests in 991d3f5, before the test refactor in fb1b3ce.

**Review by jlelong — COMMENTED** [review]
It is not easy to review the PR in detail but it looks good to me. It seems to be a quite straightforward drop-in replacement. 

Il would interesting to investigate if `unified-latex` could also be used fro completion purposes. It would make it a true alternative to LU.

**Comment by James-Yu** [comment]
> It is not easy to review the PR in detail but it looks good to me. It seems to be a quite straightforward drop-in replacement.

I fully agree. I do plan to release this UL-based structure in few days as sort of preview into a fully UL-based LW. This may limit the possible negative impact within the structurer scope.

> Il would interesting to investigate if `unified-latex` could also be used fro completion purposes. It would make it a true alternative to LU.

Indeed, it is quite possible and straightforward to use UL for completion and almost all TeX parsing parts. As to `bibtex`, I do have a plan to implement our own simple parser based on existing ones. It is far more simple than a LaTeX one.

Let me merge this and cross the finger.

**Comment by James-Yu** [comment]
It's just too unfortunate that we are unlikely to integrate `unified-latex` into LW. This package is built upon `unified`, which since `v10` only publish ESM distributions. However, either vscode or electron only supports CommonJS, no ESM for sure.

I have tried 10+ different solutions to circumvent the issue, to no vail. I will keep an eye on https://github.com/prettier/prettier-vscode/issues/3007, which should be facing the same problem. (`prettierjs` is also built on `unified`).

**Pull request merged**
