### PR TITLE
Better viewer trimming

### PR DESCRIPTION
**Pull request by James-Yu**
This PR provides a new implementation to replace the original PDF viewer trimming logic.

The old one heavily relies on Javascript computation on the size/margin of viewer, and the implementation is quite inter-twined.

This new implementation instead is CSS-based. We create a new css-var called `--trim-factor`, which will be multiplexed onto the `--scale-factor` of PDF.js for high-resolution rendering of PDF.

Further, the viewer relies on `--trim-factor` to calculate the width/height of each page, then set a negative margin to the top and left to centralize each page, effectively trimming the margins.

This PR also moves the trimming selector from main toolbar to the dropdown menu: this decision is based on the small size of empty space in the main toolbar. The previous place often caused layout glitches.

Further, the trimming selector is improved to be a numerical input, such that users have a more precise control over the trimming percentage.

Further +1, the structure of `latexworkshop.ts` is changed by extracting features in other `component` files. Clean up a bit.

### CODE REVIEW

**Comment by James-Yu** [comment]
The someday in #3754 has come. @bwegge hello! I'm not sure if you are still using this extension. If so, may I invite you to have a test on this PR? The latest artifact (as of now) can be found at https://github.com/James-Yu/LaTeX-Workshop/actions/runs/9595844297 .

**Comment by James-Yu** [comment]
I was quite confident on the new implementation until I revised #3754 and noticed so many edge but practical usages 🤣

**Comment by James-Yu** [comment]
@quoc-ho The latest commit should work well with pages of different sizes.

**Comment by quoc-ho** [comment]
There's some scrolling issue with pdf reload when trimming level is changed. Steps to reproduce:
- Open a tex file, compile, and open preview.
- Scroll to some page > 1
- Increase the trim level
- Make some small changes in the tex file and recompile

After each compile, the scrolling position will move up. This issue will disappear if the pdfviewer is closed and reopened.

**Comment by James-Yu** [comment]
> After each compile, the scrolling position will move up. This issue will disappear if the pdfviewer is closed and reopened.

Caused by a racing condition on setting the `scrollTop` of viewer container. Fixed in ec788b8.

**Comment by quoc-ho** [comment]
The newest commit makes things flicker much more than before because the first page is displayed briefly before jumping to the original location. This happens even without trimming enabled. With #4281 incorporated, the flicker is still there (but slightly less). This is a new source of flicker.

**Comment by quoc-ho** [comment]
The newest commit doesn't fix the introduction of more flicker. Moreover, the previous problem with scrolling position reappears.

**Comment by quoc-ho** [comment]
Unfortunately, the extra flicker is still there (where the first page is briefly displayed) with trimming on. Moreover, the only zoom level that works with trimming is `Automatic Zoom`. Changing the zoom level reintroduces the bug with the scrolling position and moreover, the zoom level gets changed after a reload.

**Comment by James-Yu** [comment]
Flickering is not the top priority issue to be handled in this PR. I am first working on the appearance of trimming.

Regarding zoom level, does trimming work on fit-width and fit-page? Besides auto, these two should be the only mode trimming work, as all others are the absolute percentage zooming, which trimming should not change the scale.

Further, I've tested fit-page and 200% zooming, no offset in reloading pdf found. May I know which zoom level and browser/in-editor viewer you are using?

**Comment by James-Yu** [comment]
cc8dbc3 should fix the zoom-level-reset problem. I am yet to reproduce the scrolling offset issue.

One more tip, you can use `Refresh all LaTeX PDF viewers` command to quickly reload pdfs, without needing to re-compile.

**Comment by James-Yu** [comment]
I figure (again) that the PDF.js viewer is too convoluted to make serious modifications. I unfortunately give up again.

To future me: Unless you have two weeks' free time (8h per day), don't touch trimming. Or, don't touch anything related to PDF.js scaling.

**Comment by James-Yu** [comment]
The latest commit should be working in any cases (hopefully).

The jump-to-page-1-then-back was indeed not a regression. Original implementation also behave as is. I will look into improving that after the new trimming is polished.

**Comment by quoc-ho** [comment]
Everything seems to work, even when incorporating my newest patch for the flicker! 🎉🎉🎉🎉🎉

**Comment by quoc-ho** [comment]
I celebrated too early. The issue with losing the scroll position happens when there's a landscape page in the middle. Also, sometimes, the portrait pages are aligned centrally compared to the landscape page and sometimes they are aligned on the left, seemingly depending on where the landscape page is in the viewport. And I know that it's not the main issue here, but maybe it's related: when there are landscape pages, the scrolling to top problem is more visible.

https://github.com/James-Yu/LaTeX-Workshop/assets/10014608/0b719d14-caa2-43f7-97e8-68c4e709ab50

**Comment by quoc-ho** [comment]
On this branch, Page-width/page-fit depends on the current page rather than the largest page in the document whereas on the master branch, things behave differently. So this seems to be a minor issue having to do with computing the right number.

**Comment by James-Yu** [comment]
> The issue with losing the scroll position happens when there's a landscape page in the middle.

On it.

> Also, sometimes, the portrait pages are aligned centrally compared to the landscape page and sometimes they are aligned on the left, seemingly depending on where the landscape page is in the viewport.

That was really a good catch. However, this is a pdf.js viewer issue. Same thing happens with main branch, and I confirmed on the viewer.mjs code and figured that the height and width of pages are calculated based on the current page. So the scale is not fixed for such pdfs. I don't think it's possible to fix it on the extension side though.

> And I know that it's not the main issue here, but maybe it's related: when there are landscape pages, the scrolling to top problem is more visible.

On it soon.

> Page-width/page-fit depends on the current page rather than the largest page in the document.

pdf.js viewer issue. L12614 and L12180-L12181 to be specific.

**Comment by quoc-ho** [comment]
The behavior is still different from the one in the master branch, and I think the one in the master branch is more desirable. Namely, in the master branch, the zoom level (in the case of page width/fit) might change on refresh but it only changes at most once. On the current branch, it changes whenever the current page switches from a landscape to a portrait page (or vice versa). So, a small scroll can mix everything up.

It might be the case that the behavior in the current branch is the default one for pdfjs while the one on the master branch happens to be better :).

**Comment by James-Yu** [comment]
This new implementation of trimming should be in a good shape to merge. Un-appeared bugs will be fixed.

Now will turn to 1) clean up `latexworkshop.ts` and remove/re-implement server-client communication code, 2) reduce flickering.

**Pull request merged**
