### PR TITLE
Support a builtin synctex functionality.

### PR DESCRIPTION
**Pull request by tamuratak**
This is a patch to support a builtin synctex functionality, which solves #1008. By setting latex-workshop.synctex.synctexjs.enabled to true, a builtin synctex function will be used instead of the synctex command. Although I don't think we should use the function as a default, it works somehow.

### CODE REVIEW

**Comment by James-Yu** [comment]
Awesome! Really look forward to use this one as default and remove all synctex binary related code.

Is it possible to move the synctexjs source to a new folder `src/lib` since it is a 3rd-party contribution? Also, is this javascript implementation fast enough to replace the binaries shipped with LaTeX distributions?

**Comment by tamuratak** [comment]
I have moved `synctexjs.ts` to `src/lib`. As far as I tried, it is fast enough. The main issue is the accuracy of the backward (pdf to source) synctex. We need to improve it.

**Comment by tamuratak** [comment]
Yes, we still need synctex files. We must compile tex files with `-synctex=1`.

**Comment by tamuratak** [comment]
Now, this PR works well with various latex engines, latex, pdflatex, xelatex, lualatex, and uplatex, at least for `\documentclass{article}` as far as I tested. Testing for other classes and packages are welcome.

**Comment by tamuratak** [comment]
Now, using `iconv-lite`, we can invoke synctex for a tex file whose name containing Chinese characters. This solves #495, #727, and #936.

**Comment by James-Yu** [comment]
Awesome work. Will merge and subsequent fixes if any may go another branch.

**Comment by James-Yu** [comment]
@tamuratak When you think ready, please make this feature default in the configuration. After that we can work on removing synctex binary codes from the extension.

**Comment by Astrantia** [comment]
Is it me or is this version of synctex faster ?

**Comment by tamuratak** [comment]
@James-Yu, thanks.

@Astrantia, please try. I have not measure it. If you find a case in which the built-in synctex is slow, please tell me.

**Comment by Astrantia** [comment]
@tamuratak I tried it and I think that javascript version is faster.

**Comment by tdurieux** [comment]
I'm really happy to see that my code is used it this really good plugin :)

Well done!

**Comment by tamuratak** [comment]
@tdurieux, I am glad to hear you say that. Thank you for your great coding.

**Pull request merged**
