### PR TITLE
stop using yarn

### PR DESCRIPTION
**Pull request by tamuratak**
Using different package managers induces mistakes related to release engineering. We should stop using `yarn`.

### CODE REVIEW

**Comment by tecosaur** [comment]
@James-Yu \*cough

**Comment by James-Yu** [comment]
Sorry but got too many things in real life that made me away from keyboard for months. When packaging the extenion, npm error message says
```
 ERROR  Command failed: npm list --production --parseable --depth=99999
npm ERR! missing: chokidar@2.1.8, required by latex-workshop@8.2.0
npm ERR! missing: mathjax@2.7.6, required by latex-workshop@8.2.0
npm ERR! missing: pdfjs-dist@2.2.228, required by latex-workshop@8.2.0
npm ERR! missing: strip-json-comments@3.0.1, required by latex-workshop@8.2.0
npm ERR! missing: workerpool@5.0.0, required by latex-workshop@8.2.0
npm ERR! missing: inherits@2.0.4, required by chokidar@2.1.8
npm ERR! missing: upath@1.2.0, required by chokidar@2.1.8
npm ERR! missing: graceful-fs@4.2.2, required by readdirp@2.2.1
npm ERR! missing: inherits@2.0.4, required by readable-stream@2.3.6
npm ERR! missing: process-nextick-args@2.0.1, required by readable-stream@2.3.6
npm ERR! missing: graceful-fs@4.2.2, required by fs-extra@5.0.0
npm ERR! missing: graceful-fs@4.2.2, required by jsonfile@4.0.0
npm ERR! missing: inherits@2.0.4, required by glob@7.1.4
npm ERR! missing: commander@2.20.1, required by latex-utensils@1.1.4
npm ERR! missing: mathjax@2.7.6, required by mathjax-node@2.1.1
npm ERR! missing: abab@2.0.2, required by jsdom@11.12.0
npm ERR! missing: acorn-globals@4.3.4, required by jsdom@11.12.0
npm ERR! missing: cssom@0.3.8, required by jsdom@11.12.0
npm ERR! missing: cssstyle@1.4.0, required by jsdom@11.12.0
npm ERR! missing: escodegen@1.12.0, required by jsdom@11.12.0
npm ERR! missing: acorn@5.7.3, required by jsdom@11.12.0
npm ERR! missing: symbol-tree@3.2.4, required by jsdom@11.12.0
npm ERR! missing: acorn@6.3.0, required by acorn-globals@4.3.4
npm ERR! missing: acorn-walk@6.2.0, required by acorn-globals@4.3.4
npm ERR! missing: cssom@0.3.8, required by cssstyle@1.4.0
npm ERR! missing: abab@2.0.2, required by data-urls@1.1.0
npm ERR! missing: estraverse@4.3.0, required by escodegen@1.12.0
npm ERR! missing: esutils@2.0.3, required by escodegen@1.12.0
npm ERR! missing: uuid@3.3.3, required by request@2.88.0
npm ERR! missing: ajv@6.10.2, required by har-validator@5.1.3
npm ERR! missing: psl@1.4.0, required by tough-cookie@2.4.3
npm ERR! missing: lodash@4.17.15, required by request-promise-core@1.1.2
npm ERR! missing: psl@1.4.0, required by tough-cookie@2.5.0
npm ERR! missing: mixin-deep@1.3.2, required by base@0.11.2
npm ERR! missing: set-value@2.0.1, required by cache-base@1.0.1
npm ERR! missing: union-value@1.0.1, required by cache-base@1.0.1
npm ERR! missing: extend-shallow@2.0.1, required by set-value@2.0.1
npm ERR! missing: set-value@2.0.1, required by union-value@1.0.1
npm ERR! missing: is-extendable@1.0.1, required by mixin-deep@1.3.2
npm ERR! missing: ajv@6.10.2, required by schema-utils@0.4.7
npm ERR! missing: ajv-keywords@3.4.1, required by schema-utils@0.4.7
npm ERR! missing: async-limiter@1.0.1, required by ws@5.2.2
```

`npm i` works well, but I cannot package. That is the problem for me and I can reproduce this issue on all (four) of my dev machines, though all with Windows.

**Comment by tamuratak** [comment]
1. Update the repository to the newest one. 
2. Remove all the following:

- `C:\path\LaTeX-Workshop\node_modules`
- `C:\path\LaTeX-Workshop\package-lock.json`
- Cache directory of npm, `%AppData%/npm-cache`. See [doc](https://docs.npmjs.com/cli/cache#cache).

3. Try `npm run release`

**Comment by James-Yu** [comment]
So interesting that this approach resolved the problem. I will try on my main dev machine and merge this PR if things work well.

**Pull request merged**
