### PR TITLE
Remove intellisense tricks from autoClosingPairs

### PR DESCRIPTION
**Pull request by jlelong**
This PR is related to https://github.com/James-Yu/LaTeX-Workshop/issues/2731#issuecomment-981348890

It seems that intellisense for everything involving `(`, `{`, `[` just works fine even without explicitly disabling the auto closing using https://github.com/jlelong/vscode-latex-basics/blob/898c5155fc8a657df293ec6abc19890e9c0b3247/latex-language-configuration.json#L22-L48

@tamuratak Can you test this PR? Am I missing something? That would be good news.

### CODE REVIEW

**Comment by tamuratak** [comment]
> Am I missing something? 

Without these tweaks, we see the following behavior. I am not sure it is acceptable or not:

https://user-images.githubusercontent.com/10665499/143957215-cd284ea7-7b5d-40fb-aa59-6a17610c4f4e.mov


We can also remove the same parts in other `language-configuration.json` files.

- https://github.com/James-Yu/LaTeX-Workshop/blob/02dcacc2638962c1feb6206f7b8b277c95e6de25/syntax/latex-weave-language-configuration.json#L24-L43

**Comment by jlelong** [comment]
The only broken behaviour occurs when intellisense is triggered inside `\left()`. Actually, I think the real drawback of removing these tweaks occurs when inserting `\left(   \right.` Users will have to first delete the closing `)`.

Nov-30-2021 06-17-55

The most efficient way of dealing with this use case is to keep the tweaks. As this is not actually related to intellisense, I think that these auto closing definitions should not be considered as tweaks but as real requirements for the LaTeX language. Therefore, I am in favour of keeping these definitions in the language definitions provided by the basic LaTeX language extension.

**Comment by tamuratak** [comment]
> Therefore, I am in favour of keeping these definitions in the language definitions provided by the basic LaTeX language extension.

`vscode-latex-basics` should work with other LaTeX extensions, e.g. vscode-texlab.  I am not sure these tweaks can work with the extensions.  I don't want to be bothered to install other extensions to see whether they work. Moreover, since the behavior of snippets is fragile, we might have to check every VS Code update. At least, I don't want to do that.

**Comment by tamuratak** [comment]
I think enabling LaTeX Workshop and vscode-latex-basics to have different language-configuration.json files makes things simple.

**Pull request closed without merging**
