### PR TITLE
Initial version of code actions

### PR DESCRIPTION
**Pull request by jabooth**
This PR adds a basic set of code actions that can be performed to fix simple errors detected by ChkTeX. 

Hit `cmd` + `.` over a warning to see any relevent code actions, or use the mouse to click the light bulb icon.

Best explained with a demo:

demo linting

For now I've just for common easy to fix errors. It's simple enough to extend this to more complex fixes though.

### CODE REVIEW

**Comment by James-Yu** [comment]
This feature is really a monster! Thanks so much for making it possible. Please do merge when you think it's good.

**Comment by jabooth** [comment]
@James-Yu glad you like it! I actually think the current version is pretty solid, I'll test it a little on my thesis and if I don't encounter any issues I'll merge later tonight (UK time!)

**Comment by jabooth** [comment]
OK, I've expanded this out to cover 17 of the 46 ChkTeX warnings. :)

**Comment by jabooth** [comment]
Not seeing any major issues, so going to bring this in!

**Pull request merged**
