### PR TITLE
Add support for weave.jl

### LINKED ISSUE #2128: Add support for .jnw files (LaTeX + Julia)
Latex-workshop now supports `Rnw`, i.e., regular tex file with r code.
I'm wondering whether it is possible to add more supported file types, such as `jnw`, i.e., regular tex file with Julia code.

Furthermore, when my file is a `Rnw` one, the icon `View LaTex PDF File` doesn't show after successful complication. Any suggestions?

Thanks.

### PR DESCRIPTION
**Pull request by jlelong**
This PR adds support for LaTeX + Julia files using [weave.jl](https://github.com/JunoLab/Weave.jl).

We recognize `.jnw` and `.jtexw` as file extensions.
Any recipe linked to `weave.jl` should contain `jnw|jlweave|weave.jl` in its name.

Close #2128

### CODE REVIEW

**Comment by jlelong** [comment]
@likanzhan Could you test this PR and let me know if everything is working properly?

Explanations on how to use the github version of the extension: [CONTRIBUTING.md](https://github.com/James-Yu/LaTeX-Workshop/blob/e177be953f37a101dbfeb9e96f1561c08be74bfe/CONTRIBUTING.md). Make sure to checkout the `2128-weave.jl-support` branch.

**Comment by likanzhan** [comment]
I did the following:
```
git clone -b 2128-weave.jl-support https://github.com/James-Yu/LaTeX-Workshop.git
cd ./LaTeX-Workshop
npm install --no-optional
code -n
```

In VSCode, I open a simple `jnw` file like

````
\documentclass{article}

\begin{document}

<<>>=

using InteractiveUtils
varinfo(Core)

@

\end{document}
````

and click `view` --> `command palette` --> select environment `julia`


I got the following error in the terminal:

````
┌ Warning: Some Julia code in the VS Code extension crashed with
│   e = lowering returned an error, $(Expr(:error, "\"\\\" is not a unary operator"))
└ @ Main.VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-0.15.40/scripts/error_handler.jl:5
ERROR: lowering returned an error, $(Expr(:error, "\"\\\" is not a unary operator"))
Stacktrace:
 [1] error(::String, ::Expr) at ./error.jl:42
 [2] prepare_thunk(::Module, ::Expr, ::Bool; eval::Bool) at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/packages/JuliaInterpreter/src/construct.jl:360
 [3] prepare_thunk at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/packages/JuliaInterpreter/src/construct.jl:357 [inlined] (repeats 2 times)
 [4] prepare_thunk at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/packages/JuliaInterpreter/src/construct.jl:376 [inlined]
 [5] get_next_top_level_frame(::Main.VSCodeDebugger.DebuggerState) at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/debugger_core.jl:54
 [6] debug_request(::Base.PipeEndpoint, ::Main.VSCodeDebugger.DebuggerState, ::String, ::String) at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/debugger_requests.jl:46
 [7] startdebug(::String) at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/debugger.jl:87
 [8] top-level scope at /Users/lzhan/.vscode/extensions/julialang.language-julia-0.15.40/scripts/debugger/run_debugger.jl:8
 [9] include(::Module, ::String) at ./Base.jl:377
 [10] exec_options(::Base.JLOptions) at ./client.jl:288
 [11] _start() at ./client.jl:484

Julia debuggee finished. Press ENTER to close this terminal.

````

**Comment by likanzhan** [comment]
> I have noticed that you have edited [#2149 (comment)](https://github.com/James-Yu/LaTeX-Workshop/pull/2149#issuecomment-641743686). My comments applied to the post before this edition.
> 
> Can do you do the following? Use the configuration you describe in [#2149 (comment)](https://github.com/James-Yu/LaTeX-Workshop/pull/2149#issuecomment-641743686) and run _Build LaTeX project_ from the TeX badge or the Command Palette. Then post the **complete logs** of the extension using _Show LaTeX Workshop messages_.

````
[09:43:24] Initializing LaTeX Workshop.
[09:43:24] Creating file watcher for .pdf files.
[09:43:24] Creating LaTeX Workshop http and websocket server.
[09:43:24] LaTeX Workshop initialized.
[09:43:24] Found root file from active editor: /Users/lzhan/Desktop/exp/exp.jnw
[09:43:24] Root file changed from: undefined to /Users/lzhan/Desktop/exp/exp.jnw. Find all dependencies.
[09:43:24] Instantiating a new file watcher for /Users/lzhan/Desktop/exp/exp.jnw
[09:43:24] Creating file watcher for .bib files.
[09:43:24] Parsing /Users/lzhan/Desktop/exp/exp.jnw
[09:43:24] Parse fls file.
[09:43:24] Cannot find fls file: /Users/lzhan/Desktop/exp/exp.jnw.fls
[09:43:24] Server created on 127.0.0.1:61369
[09:43:24] Adding /Users/lzhan/Desktop/exp/exp.jnw to file watcher.
[09:43:24] Snippet data loaded.
[09:43:24] LaTeX Workshop version: 8.10.0
[09:43:24] BUILD command invoked.
[09:43:24] Cannot find LaTeX root file.
[09:43:32] LOG command invoked.
[09:43:38] RECIPES command invoked.
[09:43:38] BUILD command invoked.
[09:43:38] Cannot find LaTeX root file.
[09:43:38] RECIPES command invoked.
[09:43:38] BUILD command invoked.
[09:43:38] Cannot find LaTeX root file.
````

**Comment by jlelong** [comment]
Can you try again? Note that I have added your tool and recipe definitions to the default values.

**Comment by likanzhan** [comment]
> Can you try again? Note that I have added your tool and recipe definitions to the default values.

When I try to select `view` --> `command palette` --> `Latex Workshop` related function, I always get an error like:

```
Command 'LaTeX Workshop: View LaTeX PDF file in VSCode tab' resulted in an error (command 'latex-workshop.tab' not found)
```

**Comment by jlelong** [comment]
Please post the full logs. Make sure to compile before calling view.

**Comment by likanzhan** [comment]
> Please post the full logs. Make sure to compile before calling view.

Screen Shot 2020-06-11 at 9 06 32 PM

**Comment by jlelong** [comment]
The TeX badge is missing on the very left panel. It seems like the LW extension is not properly installed. You can try

```
git clone -b 2128-weave.jl-support https://github.com/James-Yu/LaTeX-Workshop.git
cd ./LaTeX-Workshop
npm install
npm run release
code --install-extension latex-workshop-8.10.0.vsix
```

Then could you restart vscode and try again? The logs are obtained from 
Please post the complete logs of the extension. Do not truncate or alter them in particular if the paths contain non ascii characters.

74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524

**Comment by jlelong** [comment]
OK I get it. There is a conflict between the `language-weave` extension and LW as they both want to set a different languageId to the `.jnw` file.

- `language-weave` uses `Weave.jl: LaTeX`. 
- LW uses `Weave.jl` languageId

Try to deactivate the `language-weave` extension or to manually set the languageId to `Weave.jl`.

**Comment by likanzhan** [comment]
1. When I do `npm run release`, I got the following output in terminal:

````
> latex-workshop@8.10.0 release /Users/lzhan/LaTeX-Workshop
> npm run clean && npm run lint && npm run compile && vsce package


> latex-workshop@8.10.0 clean /Users/lzhan/LaTeX-Workshop
> rimraf out/ .eslintcache


> latex-workshop@8.10.0 lint /Users/lzhan/LaTeX-Workshop
> eslint --cache --ext .ts,.js .

/Users/lzhan/LaTeX-Workshop/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latex-workshop@8.10.0 lint: `eslint --cache --ext .ts,.js .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the latex-workshop@8.10.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lzhan/.npm/_logs/2020-06-11T13_44_26_240Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latex-workshop@8.10.0 release: `npm run clean && npm run lint && npm run compile && vsce package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the latex-workshop@8.10.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lzhan/.npm/_logs/2020-06-11T13_44_26_255Z-debug.log
localhost:LaTeX-Workshop lzhan$ npm run clean && npm run lint && npm run compile && vsce package

> latex-workshop@8.10.0 clean /Users/lzhan/LaTeX-Workshop
> rimraf out/ .eslintcache


> latex-workshop@8.10.0 lint /Users/lzhan/LaTeX-Workshop
> eslint --cache --ext .ts,.js .

/Users/lzhan/LaTeX-Workshop/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latex-workshop@8.10.0 lint: `eslint --cache --ext .ts,.js .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the latex-workshop@8.10.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lzhan/.npm/_logs/2020-06-11T13_44_47_017Z-debug.log

````

2. so I used the following way to install the extension.

````
vsce package  # Generates a .vsix file
code --install-extension latex-workshop-8.10.0.vsix

````

3. But the problem persists.

**Comment by jlelong** [comment]
What does `npm install` say? If it works, try,

```
npm run compile
vsce package
```

**Comment by likanzhan** [comment]
> OK I get it. There is a conflict between the `language-weave` extension and LW as they both want to set a different languageId to the `.jnw` file.
> 
> * `language-weave` uses `Weave.jl: LaTeX`.
> * LW uses `Weave.jl` languageId
> 
> Try to deactivate the `language-weave` extension or to manually set the languageId to `Weave.jl`.

I think there exists something  in the branch that is not specific to `.jnw` file, as the `TeX badge` is still missing even if I open a normal `.tex` file and the same error persists.

**Comment by jlelong** [comment]
It seems that your `latex-workshop-8.10.0.vsix` package has some issues.
What is the output of `npm run compile && vsce package`?

**Comment by likanzhan** [comment]
> It seems that your `latex-workshop-8.10.0.vsix` package has some issues.
> What is the output of `npm run compile && vsce package`?

1. `npm install`

````
up to date in 3.265s

````

2. `npm run compile`

````
> latex-workshop@8.10.0 compile /Users/lzhan/LaTeX-Workshop
> tsc -p tsconfig.json && tsc -p viewer/tsconfig.json

````

3. `vsce package`

````
This extension consists of 6859 files, out of which 4804 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /Users/lzhan/LaTeX-Workshop/latex-workshop-8.10.0.vsix (6859 files, 16.89MB)
````

**Comment by jlelong** [comment]
Great. Now run `code --install-extension latex-workshop-8.10.0.vsix`.
Quit `vscode` and open `vscode` with a `.tex` file.

Is the extension activated? See if there is anything wrong in _Toggle Developer Tools_?

**Comment by likanzhan** [comment]
> Great. Now run `code --install-extension latex-workshop-8.10.0.vsix`.
> Quit `vscode` and open `vscode` with a `.tex` file.
> 
> Is the extension activated? See if there is anything wrong in _Toggle Developer Tools_?

1. A normal `.tex` file will activate the `TeX` badge, but not the `.jnw` file.

2. To use the badge, I first open a `.tex` file to activate it. I then open a `.jnw` file.

3. I compile the file with `Recipe: Compile Jnw file` and get the following output:

````
[22:32:01] RECIPES command invoked.
[22:32:01] BUILD command invoked.
[22:32:01] Found root file from active editor: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:01] Keep using the same root file: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw.
[22:32:01] Building root file: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:01] Build root file /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:01] Recipe step 1: julia, -e,using Weave,-e,weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')
[22:32:01] cwd: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang
[22:32:01] LaTeX build process spawned. PID: 10272.
[22:32:01] RECIPES command invoked.
[22:32:01] BUILD command invoked.
[22:32:01] Found root file from active editor: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:01] Keep using the same root file: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw.
[22:32:01] Building root file: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:03] Recipe returns with error: 1/null. PID: 10272. message: ERROR: syntax: invalid character literal
Stacktrace:
 [1] top-level scope at none:0
.
[22:32:03] Cleaning auxiliary files and retrying build after toolchain error.
[22:32:03] Recipe step 1: julia, -e,using Weave,-e,weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')
[22:32:03] cwd: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang
[22:32:03] LaTeX build process spawned. PID: 10273.
[22:32:05] Recipe returns with error: 1/null. PID: 10273. message: ERROR: syntax: invalid character literal
Stacktrace:
 [1] top-level scope at none:0
.
[22:32:05] Build root file /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw
[22:32:05] Recipe step 1: julia, -e,using Weave,-e,weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')
[22:32:05] cwd: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang
[22:32:05] LaTeX build process spawned. PID: 10274.
[22:32:07] Recipe returns with error: 1/null. PID: 10274. message: ERROR: syntax: invalid character literal
Stacktrace:
 [1] top-level scope at none:0
.
[22:32:07] Cleaning auxiliary files and retrying build after toolchain error.
[22:32:07] Recipe step 1: julia, -e,using Weave,-e,weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')
[22:32:07] cwd: /Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang
[22:32:07] LaTeX build process spawned. PID: 10275.
[22:32:08] Recipe returns with error: 1/null. PID: 10275. message: ERROR: syntax: invalid character literal
Stacktrace:
 [1] top-level scope at none:0
.

````

**Comment by jlelong** [comment]
The reason why you the extension does not activate on a `.jnw` file is because you also have the `language-weave` extension. I cannot do anything about that.

Can you post the output from _View LaTeX compiler log_ ?

**Comment by likanzhan** [comment]
> The reason why you the extension does not activate on a `.jnw` file is because you also have the `language-weave` extension. I cannot do anything about that.
> 
> Can you post the output from _View LaTeX compiler log_ ?

The output of the _View LaTeX compiler log_ is 

````
ERROR: syntax: invalid character literal
Stacktrace:
 [1] top-level scope at none:0

````

**Comment by jlelong** [comment]
Compile the file in a terminal to check it works. I basically only use the command you gave me.

```
julia -e "using Weave" -e "weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')"
```

**Comment by likanzhan** [comment]
> Compile the file in a terminal to check it works. I basically only use the command you gave me.
> 
> ```
> julia -e "using Weave" -e "weave('/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw', doctype='texminted')"
> ```

The following two works but not the one you provided

```
julia -e 'using Weave' -e 'weave("/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw", doctype="texminted")'

julia -e 'using Weave; weave("/Users/lzhan/Documents/ADMIN/GirHub-Master/Julia-Master/JuliaLang/exp.jnw", doctype="texminted")'


```

And the one you provided gives the same error as _View LaTeX compiler log_.

**Comment by jlelong** [comment]
I have updated the recipe. Can you test it again?
I do not know much about Julia but I guess string must be quoted with `"` and not `'`.

**Comment by likanzhan** [comment]
> I have updated the recipe. Can you test it again?
> I do not know much about Julia but I guess string must be quoted with `"` and not `'`.

It is still not working, but I guess we are closing.

1. You are right, string should be quoted with `"` and not `'`.
2. Furthermore, the parsed argument `'using Weave' ` and `'weave()'` should be quoted with `'`. But I don't know how should we reach this in JSON.

**Comment by jlelong** [comment]
The quotes are properly added when the command is spawn from the extension.
Can you post a short `.jnw` to test the extension?

I have tried to use https://github.com/JunoLab/Weave.jl/blob/master/examples/julia_latex.texw but I get some errors

```
> julia -e 'using Weave; weave("julia_latex.jtexw", doctype="texminted")'
┌ Info: Weaving chunk 1 from line 26
└   progress = 0.0
┌ Warning: ERROR: ErrorException occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Info: Weaving chunk 2 from line 36
└   progress = 0.25
┌ Warning: ERROR: ArgumentError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Warning: ERROR: UndefVarError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Warning: ERROR: MethodError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Info: Weaving chunk 3 from line 42
└   progress = 0.5
┌ Warning: ERROR: MethodError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Info: Weaving chunk 4 from line 46
└   progress = 0.75
┌ Warning: ERROR: MethodError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
┌ Info: Weaved all chunks
└   progress = 1
[ Info: Report weaved to julia_latex.tex
```

**Comment by likanzhan** [comment]
> The quotes are properly added when the command is spawn from the extension.
> Can you post a short `.jnw` to test the extension?
> 
> I have tried to use https://github.com/JunoLab/Weave.jl/blob/master/examples/julia_latex.texw but I get some errors
> 
> ```
> > julia -e 'using Weave; weave("julia_latex.jtexw", doctype="texminted")'
> ┌ Info: Weaving chunk 1 from line 26
> └   progress = 0.0
> ┌ Warning: ERROR: ErrorException occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Info: Weaving chunk 2 from line 36
> └   progress = 0.25
> ┌ Warning: ERROR: ArgumentError occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Warning: ERROR: UndefVarError occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Warning: ERROR: MethodError occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Info: Weaving chunk 3 from line 42
> └   progress = 0.5
> ┌ Warning: ERROR: MethodError occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Info: Weaving chunk 4 from line 46
> └   progress = 0.75
> ┌ Warning: ERROR: MethodError occurred, including output in Weaved document
> └ @ Weave ~/.julia/packages/Weave/AL87K/src/run.jl:248
> ┌ Info: Weaved all chunks
> └   progress = 1
> [ Info: Report weaved to julia_latex.tex
> ```

It seems there exist some problem with the `Gadfly` package in that document.

Could you try with the following example?

[exp.jnw.zip](https://github.com/James-Yu/LaTeX-Workshop/files/4768149/exp.jnw.zip)

**Comment by jlelong** [comment]
I have tested your example and the issues I get are related to Julia and Weave.jl not the extension actually.

Trying to compile your file by hand does not work

1. When calling `weave` with `doctype="texminted"`, julia code is rendered inside the generated `.tex` file using the `minted` environment. This implies two things
   1. Add `\usepackage{minted}`
   1. Add the flag `-shell-escape` to the LaTeX compiler. See the [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk).

1. When calling `weave` with `doctype="tex"`, julia is rendered using `Verbatim` environments. For this to work, you need to include the following in the preamble of `.jnw` file

    ```latex
    \usepackage{fancyvrb}
 
   \DefineVerbatimEnvironment{juliaout}{Verbatim}{} 
   \DefineVerbatimEnvironment{juliacode}{Verbatim}{fontshape=sl}
   \DefineVerbatimEnvironment{juliaterm}{Verbatim}{}
   ```

**Comment by likanzhan** [comment]
Thanks, it is now works.
Could we add the `xelatex` engine with `-shell-escape` enabled, such as

```
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-shell-escape",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ],
            "env": {}
        },
```

and use `xelatex` as default engine in the `Compile Jnw files` recipe?
such as,

```
						{
							"name": "Compile Jnw files",
							"tools": [
								"jnw2tex",
								"xelatex"
							]
						}

```

Thanks.

**Comment by jlelong** [comment]
This is not so easy. My feeling is that all these choices should be made by the user and hence he should be responsible for defining the recipe. Only the user can decide if he wants to use case 1. or 2. as they require a few changes in the source file.

Other things to keep in mind

- `xelatex` is not a transparent drop-in replacement for `latex`. For instance, the packages `inputenc`, `fontenc`, or `textcomp` cannot be used with `xelatex`.
- The `--shell-escape` option is considered as a potential security hole, see https://tex.stackexchange.com/a/88741. 

Because of all this, I am very much tempted to remove the recipe for `.jnw` files and explain in the wiki the two approaches.

**Comment by likanzhan** [comment]
Ok, understood.

Thanks.

**Comment by jlelong** [comment]
After much thought, I have decided to add tow tools `jnw2tex` and `jnw2texminted` but no recipe. It may seem strange but the tools are tricky to define because of quotes and the recipe to be used depends a lot on the user preferences.

**Comment by jlelong** [comment]
See the new wiki entry: https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#building-a-jnw-file

**Pull request merged**
