### PR TITLE
description for big ∧ and ∨ was swapped.

### PR DESCRIPTION
**Pull request by ericrbg**
not much more to say!

### CODE REVIEW

**Comment by jlelong** [comment]
These `.json` files are actually automatically generated from https://github.com/LaTeXing/LaTeX-cwl. However this project seems not to be maintained anymore. Therefore, I maintain my own fork at https://github.com/jlelong/LaTeX-cwl for use in LW.
Could you make PR against https://github.com/jlelong/LaTeX-cwl?

**Comment by ericrbg** [comment]
I can't seem to find where in that set of files there's descriptions for the commands :(

**Comment by jlelong** [comment]
My first comment was incomplete. The documentation comes from http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt

The error comes from there. It is not clear how it can be fixed.

**Comment by ericrbg** [comment]
I've sent an email, hopefully `milde` sees this.

**Comment by jlelong** [comment]
OK, let's see if there is a way to get http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt fixed.
For now, I am closing this PR as we can nothing on our side.

**Pull request closed without merging**
