### PR TITLE
add more intuitive snippets

### PR DESCRIPTION
**Pull request by morpheusthewhite**
I think many snippets are not intuitive so I added better ones

### CODE REVIEW

**Comment by trevorgunn** [comment]
I'd prefer if all the snippets provided by the extension had a special prefix like `\` or `@` so that they don't show up whenever I type a word beginning with "in".

You can [add your own user snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets) if you want to do something different.

**Comment by jlelong** [comment]
I agree with @trevorgunn.

**Comment by morpheusthewhite** [comment]
Well then you should apply this policy to all of your snippets, from `item` to `SPG` and so on

**Comment by jlelong** [comment]
I agree that `item` looks odd. All the others are explained in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets) and follow a common pattern. Note that the prefixes are all uppercased to avoid mixup with standard typing. The `B` and `S` patterns come from [vim-latex](http://vim-latex.sourceforge.net)

**Pull request closed without merging**
