### PR TITLE
Add \textnormal shortcut which wasn't listed

### PR DESCRIPTION
**Pull request by Tvde1**

### CODE REVIEW

**Comment by Tvde1** [comment]
I see that the shortcut is also not listed on https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets

**Comment by jlelong** [comment]
These two files are deprecated. I will remove them.
Please refer to this [wiki page](https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#Font-commands).

**Comment by Tvde1** [comment]
That wiki page also doesn't include the shortcut :)

**Comment by jlelong** [comment]
Yes I have seen that. I am adding it.

**Pull request closed without merging**
