### PR TITLE
Folding range provider

### PR DESCRIPTION
**Pull request by neilsustc**
Provide section-based and environment-based folding (#263)

demo

### CODE REVIEW

**Comment by Astrantia** [comment]
@neilsustc Thanks!!!
@James-Yu Please push a new release in marketplace right away once this is merged :D

**Comment by tecosaur** [comment]
This is fantastic. Thanks @neilsustc

**Comment by Astrantia** [comment]
@neilsustc 

Actually I find some bugs with multiple environments:

```
\section*{Bug1}

\subsection{Intro} 
\begin{enumerate} % BUG 2
	\item  a
	\item  d
	\item  s
	\item  q
	\item  q
	\item  a
\end{enumerate}

\subsection{Now}
\begin{enumerate}
		\item d
\end{enumerate}

\begin{enumerate}
		\item
\end{enumerate}
```
Bug 1: The uppermost Section doesn't get fold option
Bug 2: folding enumerate folds both enumerates

**Comment by Astrantia** [comment]
Yes, the current implementation is quite buggy 😞. At least, we've got something to work on.

**Comment by neilsustc** [comment]
You are right. Some further improvements are needed.

**Comment by Astrantia** [comment]
@neilsustc no longer working on this?
@James-Yu this implementation is not working for 99% of tex files, why don't we revert to the indentation folding?

**Comment by neilsustc** [comment]
Bug 1 is easy to fix
Bug 3 might be fixed with #959 (I guess)
As for bug 2, it is a little bit tricky. It seems there is no simple way if we stick to the current "regex matching" method

I might have some time during the weekend

If the current stage is unusable for you, you can always set `editor.foldingStrategy` to `indentation` ([link](https://github.com/James-Yu/LaTeX-Workshop/issues/953#issuecomment-436583427))

**Comment by Astrantia** [comment]
@neilsustc Unfortunately changing that setting doesn't fallback to the default indentation. I already tried it, but extension still used the Provider implemented by you.

**Comment by neilsustc** [comment]
Then it is a vscode issue if you did it right. It works for me and at least another people in above link.

**Comment by iamhyc** [comment]
I am not familiar with regex, but I think there is a bug with `envRegex`. You should at least set the regex flag from `g` to `gU`.

when the flag is `g`, wrongly folded.
image


when the flag is `gU`, works correctly.
image

(regex tested on [https://regex101.com](https://regex101.com/))

**Comment by neilsustc** [comment]
There is no good solution (in regex) since both following cases are possible

```
\begin{env}
    ...
\end{env}

\begin{env}
    ...
\end{env}
```

and 

```
\begin{env}
    \begin{env}
        ...
    \end{env}
\end{env}
```

No single unified regex can handle both cases (seems to me).

**Comment by iamhyc** [comment]
> There is no good solution (in regex) since both following cases are possible
> 
> ```
> \begin{env}
>     ...
> \end{env}
> 
> \begin{env}
>     ...
> \end{env}
> ```
> and
> 
> ```
> \begin{env}
>     \begin{env}
>         ...
>     \end{env}
> \end{env}
> ```
> No single unified regex can handle both cases (seems to me).

Oh, it seems like a operation stack. but anyway, I have disabled this provider and waiting for the bug fixed :)

**Comment by neilsustc** [comment]
No

**Comment by jlelong** [comment]
Just a piece of advice, you can have a look at the function [locateMatchingPair](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/envpair.ts#L79), which deals with the problem of finding matching `\begin/\end` pairs.

**Comment by neilsustc** [comment]
Thanks for the information

**Comment by James-Yu** [comment]
I will revisit the folding logic.

**Comment by iamhyc** [comment]
Hi everyone, I make a PR to solve the folding problem with env.

Could you help check on #984 ? I think my implementation may be naive without thorough test.

Thank you!

**Comment by James-Yu** [comment]
@iamhyc It looks good for me, will merge and make minor edits.

**Pull request merged**
