### PR TITLE
Kill all tslint warns

### PR DESCRIPTION
**Pull request by innerlee**
No essential change except removes all annoying warns by tslint, happy coding!

### CODE REVIEW

**Comment by James-Yu** [comment]
Thanks for the contribution. Meanwhile, can you please branch and develop the subsequent fixes for PR? I'm always a bit hesitated to merge PRs with massive files involved, and in this case it is the base for the rest ones. What do you think?

**Comment by innerlee** [comment]
I understand the sense of hesitation. However, the changes are just formatting, mostly. A careful review may be feel safer.

**Comment by innerlee** [comment]
I will separate the two later prs from this one.

**Comment by innerlee** [comment]
the latter two prs have been decoupled from this one, and this pr is also no longer depend on the previous one.

**Pull request closed without merging**
