### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by tamuratak**
Hi,
this is a patch to add minimal tests. I heavily use `sleep` to wait for build commands and others to finish.

### CODE REVIEW

**Comment by tecosaur** [comment]
If this is added, could we also integrate a CI testing? something like Travis or Circle.

**Comment by zoehneto** [comment]
At least on travis ci you can install packages as described [here](https://docs.travis-ci.com/user/installing-dependencies/), though the obvious question is how long it would take to install texlive :)

**Comment by BreakBB** [comment]
@tamuratak I am curious why you're using `sleep` inside the tests since you wait for the Promises to resolve right before?

**Comment by tamuratak** [comment]
Rejected in https://github.com/James-Yu/LaTeX-Workshop/pull/1284#issuecomment-480711400.

**Pull request closed without merging**
