### PR TITLE
CTAN package list script (completion)

### PR DESCRIPTION
**Pull request by Swoy**
Added a script that will fetch an updated list of all packages from the CTAN repo, should make it easier to refresh this list on new releases.

### CODE REVIEW

**Comment by Swoy** [comment]
If I by chance also find it in me to compile package examples over the next months, how would you like me to structure this?
Does anyone know if the completion popup (in lack of better words) support html or Markdown from JSON?

I could add it as a prop; 'sample': '#a0poster \n this is how you use a0....'?

**Comment by Swoy** [comment]
@James-Yu I made sure it won't invalidate the json 🥇

**Comment by jlelong** [comment]
The auto-completion menu des not seem to have html neither Markdown support. Unfortunately, we are left with text only.

**Comment by James-Yu** [comment]
Any data structure you consider appropriate would be fine, though it seems that we have to push vscode for providing rich API support.

**Pull request merged**
