### PR TITLE
Improve scope names

### PR DESCRIPTION
**Pull request by jlelong**
**Warning: This is PR must not be merged.** It is basically intended for discussing scope names. 

This PR is related to #2126. 

The commit messages should be sufficiently self explanatory to make clear what the changes are.

The most noticeable change is that math text is no special highlighting anymore. This is induced by the use of `meta.math` instead of `support.class.math`.

Before: 
Capture d’écran 2020-07-02 à 15 18 16

After: 
Capture d’écran 2020-07-02 à 15 18 02

### CODE REVIEW

**Comment by tamuratak** [comment]
What is the reason you think the latter of highlighting is better?

**Comment by jlelong** [comment]
I am not sure this is better. The rendering is closer to the one in Sublime.
I think some commits are good improvements

- Use .latex as suffix scope for latex syntax
- Use support.function for standard commands
- Match \, and \; as as support.function
- Add string.other.math to highlight math delimiters

For the rest, this is a question of taste and it is unclear to me.

**Comment by tamuratak** [comment]
As a user, I do not want highlighting to change without specific reasons. The consistency of the names of tokens does not justify the change. For a user getting used to the current highlighting, it is the correct one, even if it is not correct in semantics.

**Comment by jlelong** [comment]
@tamuratak I think you are right. I will only keep the following changes 

- Use `.latex` as suffix scope for the latex syntax (no visual changes here)
- Match `\,` and `\;` as as support.function

I personally prefer the second screenshot using `meta.math` instead of `support.class.math` but I do agree that this purely a matter of taste and we should not change highlighting for this reason. So I will not keep this commit for now.

**Comment by tamuratak** [comment]
Thank you.

**Comment by tobiasdiez** [comment]
The syntax highlighting strongly depends on the chosen theme. Because of the inconsistency of the scope names, latex text looks rather awful in many themes. Moreover, some other functions and extensions (e.g. spellchecker) rely on the scope. For these reasons I would argue it is important that the scope names match with their intended use.

As far as I understand the VS code architecture, the extension should specify the scope names and the code styling is delegated to themes. Thus, if you would like to keep (or change) the way latex code looks, then a designated latex theme would be a good choice I guess.

**Comment by jlelong** [comment]
> As far as I understand the VS code architecture, the extension should specify the scope names and the code styling is delegated to themes. Thus, if you would like to keep (or change) the way latex code looks, then a designated latex theme would be a good choice I guess.

The user chooses its preferred theme and there is no way to keep the old rendering if we modify the scopes.

**Comment by tobiasdiez** [comment]
What I meant is that (to my understanding) a language extensions shouldn't worry about the code styling and instead specify the correct scopes. The styling is the job of the theme. 

Anyway, if the user prefers the old styling then he can specify something along the following lines in his settings:
```
    "editor.tokenColorCustomizations": {
        "[Default Light+]": {
            "textMateRules": [
                {
                    "scope": "meta.math",
                    "settings": {
                        "foreground": "#267F99"
                    }
                }
            }
     }
```

**Comment by jlelong** [comment]
I have updated my comment to make it clearer and indeed only the user can customize the theme colors.

**Comment by jlelong** [comment]
> What I meant is that (to my understanding) a language extensions shouldn't worry about the code styling and instead specify the correct scopes. The styling is the job of the theme.

From a design perspective I do agree with you but legacy makes things less clearer. If the styling changes, we will get a lot of issues complaining or at least discussing these changes, which I really do not want. 

From your original post, here is what I suggest to address

- [ ] Fix the `.tex` vs `.latex` scope suffix
- [ ] Add the `meta.math` scope on top of `support.class.math` for maths regions. This will not change highlighting unless the user explicitly customize the `meta.math` scope
- [ ] Fix classification of `\,` and match `\;`
- [ ] Highlight maths delimiters
- [ ] Add a meta tag for optional arguments of standard commands
- [ ] Do not highlight file names in `\input, `\include`, `\VerbatimOut` to remove the use of `support.class.latex`. Any suggestion of an other scope?
- [ ] Highlight `+,-,*,/,_,^` in math mode

What I do not plan to address for now

- `keyword.control` vs `support.function`
- `constant.character.math.tex` vs `constant.other.general.math.tex`
- arguments of cite commands using `constant.other.reference.citation.latex`

**Comment by jlelong** [comment]
I would love to have feedback on these changes. There should be very little visible differences for the user. I would like to merge/close this PR and the related issue by the end of the week as I do not really have more time to devote to it.
@tamuratak What is your opinion on the changes? 

It seems that when assigning two scopes to an element, the first one (going from left to right) that is actually defined by the theme takes precedence on the other. However, I did not find any documentation on that.

**Comment by tamuratak** [comment]
I am against changing the color of `$`. 

With `Default Light+`.

Before:

スクリーンショット 2020-07-08 17 37 55

After:

スクリーンショット 2020-07-08 17 36 04

**Comment by jlelong** [comment]
OK, the commit is reverted. I am afraid we cannot do better without altering the current styling.

@tobiasdiez If one specific scope really creates an issue when using other extension, please open a new issue for this one and will try yo figure out what we can do. For the moment, I am merging this PR and closing the related issue.

**Pull request merged**
