### PR TITLE
Update default settings

### PR DESCRIPTION
**Pull request by XuehaiPan**
1. Add biber to latex.tools, and "pdflatex ➞ biber ➞ pdflatex × 2" to latex.recipes.
2. CHANGE default latex.outDir to "%DIR%/out".

### CODE REVIEW

**Comment by jlelong** [comment]
I am against changing the default value for `outDir`. Setting `outDir` to something different than `%DIR%` may cause serious issues when compiling bibliographies and glossaries.

**Comment by XuehaiPan** [comment]
> I am against changing the default value for `outDir`. Setting `outDir` to something different than `%DIR%` may cause serious issues when compiling bibliographies and glossaries.

I have added `-output-directory=%OUTDIR%` to `latexmk`, `pdflatex` and `biber`.

For `bibtex`, the command have been changed to:

```json
{
  "name": "bibtex",
  "command": "bibtex",
  "args": [
    "out/%DOCFILE%"
  ],
  "env": {
    "BIBINPUTS": "%OUTDIR%:"
  }
}
```

For `glossary` package, build with `latexmk -output-directory=%OUTDIR%` can solve the issue you mentioned. Or complie with command `makeglossaries -d %OUTDIR% %DOCFILE` .

For `minted` package, need to add option `\usepackage[outputdir=out]{minted}`.

**Comment by XuehaiPan** [comment]
Complied with `"pdflatex ➞ makeglossaries ➞ bibtex ➞ pdflatex × 2"` while `outDir="%DIR%/out"`.

The source file is copied from overleaf.

Screenshot 1
Screenshot 2
Screenshot 3

**Comment by jlelong** [comment]
There are many issues in this repo concerning the use of  `outdir` (`-output-directory` is just a synonym) and subfiles and/or glossaries. I am against changing making any non necessary change in the definition of the recipes as it will create troubles for many users.

Btw, I cannot see the point in adding `pdflatex ➞ biber ➞ pdflatex × 2` whereas it is sufficient to use `latexmk`.

I am closing the PR as you can always make the changes in your own configuration.

**Pull request closed without merging**
