### PR TITLE
Support preview for $$...$$

### PR DESCRIPTION
**Pull request by jlelong**
@tamuratak Can you have a look at this to make sure I have understood everything right?

### CODE REVIEW

**Comment by trevorgunn** [comment]
This doesn't work because the current regex doesn't capture `$$...$$`, it captures `$$...$` plus other undesirable behaviour which I have outlined in my previous comment https://github.com/James-Yu/LaTeX-Workshop/issues/1278#issuecomment-480553004

The regex I posted: `(?<!\$|\\)\$(?!\$)(?:\\.|[^\\])+?\$|\\\(.+?\\\)|\$\$(?:\\.|[^\\])+?\$\$` (which goes in lines 530 and 545 in your version of the file) fixes this and I would have tried to send a pull request with similar changes to yours except I ran into some unusual behaviour:

example

I wasn't sure what could be causing this. It turns out this was there before I made any changes. Somehow the cursor is passed to MathJax as well as the tex.

**Comment by tamuratak** [comment]
It is difficult to know which `$$` is the start of math environment. We must parse entire TeX document to know that.

```
$$
a
$$
b
$$
c
$$
```


So, we had better leave `$$` unsupported.

I want to use @trevorgunn's regex to prevent hovers on `$$`.

**Comment by trevorgunn** [comment]
That's another good point. If we keep the new code in stripTex and use my regex, we will be able to handle $$...$$ as long as both pairs of $$'s are in the same line and otherwise it will ignore it. This might be an acceptable compromise.

**Comment by tamuratak** [comment]
@jlelong, if you want to modify complex code base like hover preview, please consider writing unit tests seriously. Without tests, it is difficult to make sure these PRs works well. 

#969 is out of date now. I will renew it if you want.

**Comment by jlelong** [comment]
@tamuratak I fully agree with regarding unit tests. Unfortunately, this is worth it only if we can write exhaustive unit tests and this is far beyond the time we devote the development of this extension. All the more so as, we would need both unit and functional tests to validate most of LW's features.

@trevorgunn I have the feeling we kind of over think on the  `$$` preview issue. Preview **is triggered by the user**, so this is up to the user to hover on opening `$$` and not on closing ones. In response to [comment](1284#issuecomment-480635936), there is no need to parse the whole document to compute matching pairs. With this is mind, I cannot find a case in which the user hovers on a valid position and the preview is badly rendered. If so, post a minimal working example.

> This doesn't work because the current regex doesn't capture `$$...$$`, it captures `$$...$` plus other undesirable behaviour which I have outlined in my previous comment https://github.com/James-Yu/LaTeX-Workshop/issues/1278#issuecomment-480553004

`$$....$$` are not detected by the same regex as `$..$`. First, we test `$$...$$` and if there is no match we use the regex. See the function [findOverOnTex](https://github.com/James-Yu/LaTeX-Workshop/blob/b47ccca38821a596ee960c4c5c11807ddad33c4c/src/providers/hover.ts#L398).

@trevorgunn for the cursor issue, see this variable `latex-workshop.hover.preview.cursor.enabled`.

**Comment by tamuratak** [comment]
@jlelong  if writing tests harms your motivation, I do not push that strongly. Keeping motivation has the highest priority for OSS development.

**Comment by trevorgunn** [comment]
@jlelong This is the test file I am using

    \documentclass{article}

    \begin{document}
      Double dollar signs match from the first to third $$abcd$$

      Matching between double dollar signs $$abc$$ def $$ghi$$

      Escaped dollar signs are still caught: \$2 is $1 + 1$ dollars

      $$
      eq^1
      $$
      This should not be hover-able.
      $$
      eq_2
      $$
    \end{document}

Each group is its own minimal test.

Current behaviour (master branch):
 - First line hovers on `$$abcd$` and displays `$abcd` (which we know already)
 - Second line hovers on `$$abc$` and `$def$` and `$ghi$`
 - Third line hovers between `$2 is$`
 - Fourth group does nothing

With your changes (preview branch):
 - First three lines have the same behaviour
 - Fourth group will hover on the first second and third pair of `$$`. First and third do what we want, second gives the "This should not be hover-able." text

With your changes + adding negative look-arounds to the regex (i.e. the first `\$` becomes `(?<!\$|\\)\$(?!\$)`:
  - first line behaves well although causes issues hovering at the last two dollar signs
 - second line will capture `$$ def $$` if you hover at the second pair of dollar signs but is otherwise okay
 - third line is okay
 - fourth group same as above

Treating `$$...$$` as an inline hover avoids this issue of hovering at the second pair of `$$` but won't handle multiple lines. I think `$$...$$` has enough quirks that it will be hard to get it exactly right. So far treating `$$...$$` inline only has had the best behaviour in my opinion.

**Comment by jlelong** [comment]
@tamuratak To be clear I am in favour a TDD. For LW, it seems to be a really tough work and I do not know how to use tests with CI for vscode's extensions.

@trevorgunn thanks for your examples and detailed explanation, I will finish this in the coming days.

**Pull request merged**
