### PR TITLE
The afformentioned keybindings

### PR DESCRIPTION
**Pull request by tecosaur**
Here it is at last! Have some more ideas but here's V1 at least. 
Edit: For the sake of referencing this stuff comes from #809.

### CODE REVIEW

**Comment by Astrantia** [comment]
@tecosaur I would suggest to add readonly's too:
https://github.com/neilsustc/vscode-markdown/blob/master/package.json#L60

**Comment by tecosaur** [comment]
That seems like a decent idea. I'll do that.

**Comment by jlelong** [comment]
The following keybindings `ctrl+e`, `ctrl+i`, `ctrl+u`, `ctrl+b` are already defined by vscode, see the _Keyboard shortcuts_ menu. We should only keep the version with the prefix `ctrl+l`.

**Comment by tecosaur** [comment]
I did consider that. However the `ctrl+b` etc. keybindings have the following `when` condition: `editorHasSelection`. This means that it will only take effect if text has been selected then they keybinding pressed. In all other situations, the default actions will be unaffected. 
Sinc only in that situation will that shortcut actually be active I felt it was relatively safe adding `ctrl+b` etc. as keybindings. From my use so far this has not caused any issues.

**Comment by tecosaur** [comment]
Forgot about those taking selected text. I'll get on that :)

**Pull request merged**
