### PR TITLE
Change CONTRIBUTING.md to use npm instead of yarn

### PR DESCRIPTION
**Pull request by trevorgunn**
Related to 8487998.

### CODE REVIEW

**Comment by James-Yu** [comment]
I'm not sure if other contributors still use `yarn`, so removing `yarn.lock` seems a bit over-confident. Any idea?

**Comment by trevorgunn** [comment]
I know Jerome said he didn't: https://github.com/James-Yu/LaTeX-Workshop/pull/1317#issuecomment-483812157 neither does Tecosaur: https://github.com/James-Yu/LaTeX-Workshop/pull/1274#issuecomment-479560482

I am not sure about Tamura.

Maybe we should only update `CONTRIBUTING.md`. There doesn't appear to be any issue with keeping both yarn and npm lockfiles. (https://stackoverflow.com/a/44904494)

Should I push the changes?

**Comment by James-Yu** [comment]
Yes, I think retaining the file for a while is a safe bet.

**Comment by tamuratak** [comment]
If I use `npm` instead of `yarn`, the following always fails:
```shell
npm install
vsce package
```
log:

```log
Executing prepublish script 'npm run vscode:prepublish'...

> latex-workshop@7.0.2 vscode:prepublish /Users/tamura/src/github/LaTeX-Workshop
> sh minify.sh && rm -rf out/ && webpack --mode production

Hash: f68db36006110ecbaf19
Version: webpack 4.33.0
Time: 36949ms
Built at: 07/07/2019 12:12:50 PM
        Asset      Size  Chunks             Chunk Names
    1.main.js   725 KiB       1  [emitted]  vendors~pdfjsWorker
1.main.js.map  2.39 MiB       1  [emitted]  vendors~pdfjsWorker
      main.js   965 KiB       0  [emitted]  main
  main.js.map  3.11 MiB       0  [emitted]  main
Entrypoint main = main.js main.js.map
  [0] external "path" 42 bytes {0} [built]
  [1] external "vscode" 42 bytes {0} [built]
  [2] external "fs" 42 bytes {0} [built]
 [11] ./src/utils.ts 1.81 KiB {0} [built]
[115] ./src/main.ts 24.8 KiB {0} [built]
[116] ./src/commander.ts 32.6 KiB {0} [built]
[317] ./src/providers/completion.ts 7.52 KiB {0} [built]
[324] ./src/providers/codeactions.ts 6.89 KiB {0} [built]
[325] ./src/providers/hover.ts 26.5 KiB {0} [built]
[329] ./src/providers/docsymbol.ts 1.26 KiB {0} [built]
[330] ./src/providers/projectsymbol.ts 1.08 KiB {0} [built]
[331] ./src/providers/structure.ts 11.7 KiB {0} [built]
[332] ./src/providers/definition.ts 3.71 KiB {0} [built]
[333] ./src/providers/latexformatter.ts 8.09 KiB {0} [built]
[334] ./src/providers/folding.ts 4.15 KiB {0} [built]
    + 330 hidden modules
 ERROR  Command failed: npm list --production --parseable --depth=99999
npm ERR! missing: mathjax@2.7.5, required by latex-workshop@7.0.2
npm ERR! missing: mathjax@2.7.5, required by mathjax-node@2.1.1
```

The following works:
```shell
rm package-lock.json 
yarn install
vsce package
```
@trevorgunn  do you succeed to execute `vsce package` with `npm`?

**Comment by trevorgunn** [comment]
No, I get the same error that you have.

**Pull request merged**
