### PR TITLE
Formatting towards eslint

### PR DESCRIPTION
**Pull request by jlelong**
See #1538 to know what has already been done.

It has implied quite a lot of changes, so I would rather have a few people test before being merged.

### CODE REVIEW

**Comment by tamuratak** [comment]
Please commit and push `package.json` also.

**Comment by jlelong** [comment]
If everyone is fine with this, I suggest to merge these changes and move on to more stylistic rules later.

**Comment by tamuratak** [comment]
Please revert the changes to files `src/lib/**/*.ts` too.

**Comment by jlelong** [comment]
Everything should be fine now. @James-Yu  @tamuratak  are you ok with merging?

**Comment by tamuratak** [comment]
Warnings `warning  Unexpected any` make us miss other warnings. Let's turn off `@typescript-eslint/no-explicit-any` in the first stage and consider what we can do later.

**Comment by jlelong** [comment]
OK I have turned `@typescript-eslint/no-explicit-any` off but we should take some time to investigate this. Any more comments before merging?

**Comment by tamuratak** [comment]
No. It seems to work well.

**Pull request merged**
