### PR TITLE
Include further information from LaTeX log in VSCode problems view

### PR DESCRIPTION
**Pull request by Vogel612**

### CODE REVIEW

**Comment by James-Yu** [comment]
Thank you very much for your contribution! Currently I've no access to development computers. Will perform a review and merge very soon(TM).

**Comment by James-Yu** [comment]
Sorry I cannot merge this PR. The 'state machine' is missing log messages, at least the first one. In addition, I cannot get the purpose of `remainingEmptyLines`. I understand it's value represents the previous log state. However, how does this state influences subsequent parsing?

**Comment by Vogel612** [comment]
I'll fix those and reopen the PR, unless you object.

**Comment by James-Yu** [comment]
Sure please go ahead. Happy to see any improvements.

**Pull request closed without merging**
