### PR TITLE
Syntax highlight for BibTeX style language (.bst)

### PR DESCRIPTION
**Pull request by zepinglee**
This is a naive implementation of language support for BibTeX style (.bst files).

### CODE REVIEW

**Comment by jlelong** [comment]
This is a good initiative! I tried the syntax highlighting on `IEEEtran.bst` and in some sections the highlighting is weird. I do not know much about `bst` syntax so I may be wrong.  Could you check that?

Capture d’écran 2019-12-14 à 20 47 21

Capture d’écran 2019-12-14 à 20 49 19

**Comment by zepinglee** [comment]
Thanks for your feedback! The highlighted words in your two screenshots are native BibTeX entry types and fields that are defined in `plain.bst`, `unsrt.bst`. Thus the one additionally defined in 'IEEEtran.bst' are not correctly highlighted. I'll dig into the vscode APIs to get them into consistency.

**Comment by jlelong** [comment]
Syntax highlighting might be a tricky. I have spent a lot of time working on the language definition files for `.tex` and `.dtx`, so I may be able to help if you tell more about the `bst` syntax.  In my screenshost,

- would you expect everything inside `ENTRY` to be highlighted or to remain white?
- same question for the `FUNCTION` lines?

**Comment by zepinglee** [comment]
The `ENTRY` command declares its attributes of an entry: fields, integers and strings. 
```
ENTRY
  { field1 field2 ... }
  { int1 int2 ... }
  { string1 string2 ... }
```
It works like a Python class definition:
```Python
class Entry:
    Field field1, field2
    int int1, int2
    str str1, str2
```
The member attributes are not highlighted in the official python syntax of VS Code. Thus everything in the `ENTRY` command remains white now.

The `FUNCTION` command is a function declaration. It is now correctly highlighted as `storage.type.function.bst` and `entity.name.function.bst`.

**Comment by jlelong** [comment]
Great! There is still an issue with `or` being highlighted as a logic keyword even in the middle or word.

Capture d’écran 2019-12-16 à 18 08 17

**Comment by zepinglee** [comment]
I'm planning to write a set of unit tests like https://github.com/microsoft/TypeScript-TmLanguage/tree/master/tests to avoid such mistakes.

**Comment by jlelong** [comment]
That would be awesome but it is a tough work!

**Pull request merged**
