### PR TITLE
Migrate to MathJax v3.2

### PR DESCRIPTION
**Pull request by tamuratak**
- Migrate to MathJax v3.2. 
- Enable an option to load MathJax extensions.

@jlelong could you try this branch? If you see any issue, please tell me.

Known issues:

- `$a \\ b$`: a line break is not rendered.  Line breaks in math environments are well-rendered.

### CODE REVIEW

**Comment by jlelong** [comment]
> @jlelong could you try this branch?

I will but it may not be before a few days.

**Comment by tamuratak** [comment]
I am going to merge this PR this weekend.

**Comment by jlelong** [comment]
Sorry for the long delay. I did a few tests and everything looks fine too much but as I do not really use this feature usually, I am probably not a good tester.

**Comment by tamuratak** [comment]
Thank you. I will merge this PR.

**Pull request merged**
