### PR TITLE
Merge latex-utilities with LaTeX-Workshop

### PR DESCRIPTION
**Pull request by viktorstrate**
> This pull request is a result of the discussions in issue #841

This pull request currently merges the code from [latex-utilities](https://github.com/viktorstrate/vscode-latex-utilities) which handles shortcuts for keywords like `\textbf`, `\textit`, `\underline`.

For latex-utilities to be fully merged, we should find a solution to automatically add `\item` when enter is pressed. But I think @jlelong is working on that, on the 'item' branch, see #847.

### I've updated the yarn.lock
I have also regenerated the yarn.lock, as I could not download all the packages, because my version of node was too new. Below is the output before I updated the file. I haven't thoroughly tested the extension though.

```
yarn install v1.10.1
[1/5] 🔍  Validating package.json...
warning latex-workshop@5.10.2: The engine "vscode" appears to be invalid.
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.11.0"
error Found incompatible module
```

### CODE REVIEW

**Comment by jlelong** [comment]
Great! It seems that the toggle feature is not robust to nested `{...}`.

For instance, if you have
```
\underline{Some text with {\em braces} and more}
```
capture d ecran 2018-10-04 a 22 12 59

and call `toggleSelectedKeyword('underline')`, you get

capture d ecran 2018-10-04 a 22 11 27

It reminds me of bad headaches!

**Comment by tecosaur** [comment]
I think this can be solved by changing the regex pattern match to require curly brackets to be matched.
This is what's happening at the moment with `\\keyword{(.*?)}`:
image

Here's a different pattern: `\\keyword(\{)(.*)(\})`
image
_NB: you want match group 2 from this_

Hope that helps

**Comment by jlelong** [comment]
Thinking of it again, you can probably use the function [getLongestBalancedString](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/structure.ts#L11) to find the matching `}` once `\keyword{` is localized. Hope that helps.
You may need to move `getLongestBalancedString` somewhere in the extension.

**Comment by tecosaur** [comment]
Perhaps use the regex match `\\keyword{(.*)}` then apply `getLongestBalancedString`? In my mind that should work.

**Comment by viktorstrate** [comment]
@tecosaur Yes, that should not be that hard to implement, when we already have the `getLongestBalancedString`.

**Comment by viktorstrate** [comment]
I have merged with master and fixed removing of tags with nested tags inside.

The code doesn't search further than the current line. If it finds a tag that is not closed off on the same line, then the closing bracket will not be removed. And if the cursor is inside a tag that is opened on a previous line, then it will not register it, and theirfore add a new tag.

I do not want to search the whole file for tags as it might be slow, but maybe an incremental approach could be used to check previous lines, only if it sees a dangling end bracket, or check the next lines, if `getLongestBalancedString` doesn't find the matching bracket.

**Comment by jlelong** [comment]
The single line approach for tags toggling looks fine too me. I guess very few people use hard line wrapping.

**Pull request merged**
