### PR TITLE
(#92) Add LaTeX Workshop prefix in quick menu

### PR DESCRIPTION
**Pull request by James-Yu**
This PR adds a `LaTeX Workshop: ` prefix to commands in quick menu.
image

Should the citation browser be added as a vscode command or as is?

### CODE REVIEW

**Comment by James-Yu** [comment]
Better!
image

**Comment by jabooth** [comment]
@James-Yu 

> Should the citation browser be added as a vscode command or as is?
 
Yes I think it should be there! Any command from LaTeX Workshop should really be exposed this way I feel.

**Comment by jabooth** [comment]
@James-Yu haha you're too fast for me to keep up! 😉

**Comment by jabooth** [comment]
@James-Yu I think we should maybe remove `LaTeX Workshop Actions` from this list, it seems pretty redundant now? It should still exist to be accessable from right click, but for the top level command it doesn't really have a role?

**Comment by James-Yu** [comment]
That would be a bit difficult. afaik the quick menu shows all vscode commands, and only these commands can be added to right click context menu and status bar click command. Will check the API again to see if there are ways to overcome it.

**Comment by jabooth** [comment]
Is there an API to trigger the quick menu with a string in it?

So we could trigger with `>  LaTeX Workshop` pre-inserted which will give you exactly the above?

**Comment by jabooth** [comment]
Ohh I mis-read, we need a command for the context menu click so this wouldn't work would it... :|

**Comment by James-Yu** [comment]
I'm afraid this is the best we can achieve

image

**Comment by jabooth** [comment]
Hmm maybe we could we do:
```
LaTeX Workshop: Show all actions
```
So it's consistent with the others? Idk though, it's minor :)

**Comment by James-Yu** [comment]
Sounds good. A small tweak

**Pull request merged**
