### PR TITLE
add some details into commands in amsmath_cmd.json

### PR DESCRIPTION
**Pull request by tamuratak**
add some details into commands in `data/packages/amsmath_cmd.json`.

### CODE REVIEW

**Comment by jlelong** [comment]
All `_cmd.json` files are automatically generated from [`cwl` files](https://github.com/LaTeXing/LaTeX-cwl/). So any change in these files will lost when we update them. With this in mind, your PR may get lost in the future. The same applies to #1303.

**Comment by James-Yu** [comment]
What about we introduce a new file for the package, e.g., `amsmath_msg.json` or other names apply, to store the custom information? The json objects stored here can be merged with those in `_cmd.json`, and changes persist through potential future script re-runs.

**Comment by tamuratak** [comment]
These PRs are generated by a script. So, I will try to rewrite scripts under `dev` into ones generating these details and documents.

**Comment by jlelong** [comment]
@tamuratak do you say that you have a way to retrieve the details automatically from somewhere else?

@James-Yu an other and perhaps a little simpler approach would be to modify the scripts in `dev` to first load the `_cmd.json` if it exists to retrieve the `details` and `documentation` fields and then insert these fields into the new generated file from the `cwl`.

**Comment by tamuratak** [comment]
Yes, from this file, http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt. We have generated `data/unimathsymbols.json` from this file.

**Comment by tamuratak** [comment]
See #1305.

**Pull request closed without merging**
