### PR TITLE
Add command to switch between equation environments.

### PR DESCRIPTION
**Pull request by trevorgunn**
I've updated #1360 to use `envPair.locateMatchingPair()`. Functionality should remain the same.

Again, I'm creating a new command because I don't believe the current commands (e.g. `latex-workshop.select-envname`) can be made to work with `\[ ... \]` well.

### CODE REVIEW

**Comment by trevorgunn** [comment]
There are some issues with inline switching that need to be resolved.

**Comment by trevorgunn** [comment]
I may do some more testing if I think of any potential issues, but the latest commit resolves all the issues I had.

**Comment by jlelong** [comment]
This is a very interesting feature but I would like to make it work with any environment not just the ones listed in `equationEnvironments`. Maybe we could the `suggestions` computed in the environment completer, see [environment.ts](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/environment.ts). I still need to think about it.

**Comment by trevorgunn** [comment]
Between the current functionality of `latex-workshop.select-envname` and this command, I'm not sure which use cases what you have in mind would address.

**Comment by jlelong** [comment]
I would like to merge this new functionality with `latex-workshop.select-envname` but as you pointed out it seems quite difficult. One possible solution would be 
- to use your new function for switching between `\[....\]` and `\begin{} .... \end{}` while leaving a double cursor inside the `{}`
- use `latex-workshop.select-envname` to change environment name.
Ideally, I would like to have the two features wrapped into the same command.

**Pull request closed without merging**
