### PR TITLE
Add keyboard shortcuts for frac and partial

### PR DESCRIPTION
**Pull request by 1900011604**
Two small changes, maybe you could change them to `ctrl+m ctrl+f` and `ctrl+m ctrl+p`

### CODE REVIEW

**Comment by 1900011604** [comment]
I will give a better pull-request in July, adding support for `\sqrt` and maybe some other snippets.

**Comment by jlelong** [comment]
Keybindings are very personal. We do not want to define new ones inside the extensions. So please, define them in your own settings as explained #2763.

**Comment by 1900011604** [comment]
`vscode.commands.registerCommand('latex-workshop.shortcut.frac', () => extension.commander.toggleSelectedKeyword('frac'))`

I cannot define them as you did not provide the command like `latex-workshop.shortcut.frac`

**Comment by jlelong** [comment]
You do not need the `latex-workshop.shortcut.frac` function. In your `keybindings.json` file, add

```json
{
  "key": "cmd+m ctrl+f'",
  "command": "editor.action.insertSnippet",
  "args": { "name": "fraction" }
}
```

**Pull request closed without merging**
