### PR TITLE
Make version numbers in changelog links

### PR DESCRIPTION
**Pull request by tecosaur**
This just makes the version numbers in the changelog link to the diffs. For an example see https://github.com/tecosaur/LaTeX-Utilities/blob/master/CHANGELOG.md it's minor but it's nice

New versions will obviously need similar lines added.

### CODE REVIEW

**Comment by jlelong** [comment]
Not sure this is really useful as only advanced users may actually be interested in diffs between releases and for sure they can access directly using `git`.

**Comment by tecosaur** [comment]
Eh. I figured why not. It's a bit nice, and I can't see any drawbacks. Not a big deal either way.
Personally I like being able to just click on a version in the changelog and see all the changed made.

**Comment by jlelong** [comment]
I will leave this to @James-Yu as he is the one who actually writes the `README.md` file.

**Comment by tecosaur** [comment]
@James-Yu sorry to bother you again but also, \*cough

**Comment by James-Yu** [comment]
Thanks for the ping. I consider this is a good addition, yet I personally do not have interest in maintaining such a git diff link when newer versions are published. Any automation tools for this task?

**Comment by tecosaur** [comment]
For keeping something like this up to date, what comes to mind is something like this:

https://github.com/github-changelog-generator/github-changelog-generator
or
https://github.com/conventional-changelog/standard-version
or
https://github.com/CookPete/auto-changelog

**Pull request closed without merging**
