### PR TITLE
Flicker free refresh

### PR DESCRIPTION
**Pull request by James-Yu**
This is a re-implementation of #4295 , following the discussion from https://github.com/James-Yu/LaTeX-Workshop/issues/4415#issuecomment-2390389131, and more importantly, migrating (reads: copy-and-paste) codes from https://github.com/tamuratak/latex-toybox/

In our previous implementation, we inject into PDF.js viewer refreshing logic to prevent flickering during PDF refresh. It caused a few issues, for example, spreading mode bounding box computation as in #4415 .

@tamuratak proposed a very elegant and non-intrusive solution for the problem in his maintaining branch by first creating images of visible PDF pages and masking them on top of canvas, then removing them once all pages are rendered. We "shamelessly" copy the idea and code.

@quoc-ho may you take a look and have a test on this branch and see if there are issues to fix? Many thanks.

### CODE REVIEW

**Comment by quoc-ho** [comment]
Wow. So fast! Thanks!!! 

There's one problem though: when trimming is on, the mask has the wrong dimension.


https://github.com/user-attachments/assets/6127f3ef-6d9c-4264-9c2e-e81bce19e950

**Comment by James-Yu** [comment]
Yeah I forgot that we are using CSS-based trimming. This latest commit should fix the problem 🤣

**Comment by quoc-ho** [comment]
Thanks! That fixes the previous problem. But on some pages, the mask is off by a couple of pixels. The problem seems to appear (mostly) on every other pages. See the attached video.


https://github.com/user-attachments/assets/a3c8902d-5cdb-4e1b-8398-994a759c2eb5

**Comment by James-Yu** [comment]
Done!

It turns out that the offset values can only be integer values, but the center position of dom can be sub-pixel. In the latest commit, we use `getBoundingClientRect()` to obtain the floating values of the position and size of dom.

**Comment by quoc-ho** [comment]
Unfortunately, when we scroll all the way to the top, then the position of DOM is calculated correctly. But when we are in the middle of a page, then it's wrong. See video below.


https://github.com/user-attachments/assets/8d45f5e5-85ee-445a-b3bc-ad672f8eaa90

**Comment by James-Yu** [comment]
This ... should work? Checked a few use cases.

I noticed one issue: when spreading is on, auto-width seems to be a bit wider than should be. It's not related to this PR, yet I will work on it later.

**Comment by quoc-ho** [comment]
Very awesome!

One last thing (hopefully): if you scroll all the way down and then refresh pdf, the position of the mask is wrong, resulting in the view being shifted briefly. This doesn't happen when the scroll position is not completely bottom.


https://github.com/user-attachments/assets/f712d522-7fc3-4367-be70-efeda0526154

**Comment by James-Yu** [comment]
Nice catch! This should be caused by pdfjs randomly destroying the last page and add it back with a small period when the page bottom margin of 10px is not added. The latest commit adds an invisible anchor div to cover the margin space.

Indeed, there is a better but behavior-changing solution: remove the 10px bottom margin of the last page, so that there is no margin in the top and at the bottom. If so, there's no need to use this anchor workaround. However, I have not settled the thought on the margin change.

**Comment by quoc-ho** [comment]
The experience is so smooth! Best pdf viewing experience ever! 

I noticed one issue: when spread mode is on and the tab being refreshed is not visible, synctex fails after a couple of refreshes. This does not happen when spread mode isn't on. The error (from the webview developer tools) is

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getPagePoint')
    at callSynctex (synctex.js:32:65)
    at pageDom.onclick (synctex.js:46:21)
```

I checked the DOM but the mask seems to be correctly removed already. So not sure what the cause is.

**Comment by James-Yu** [comment]
That's strange. Anyways this commit should prevent the error log.

I think the new implementation should be ready. Good to push to users.

**Comment by quoc-ho** [comment]
I want to clarify that reverse synctex (pdf -> tex) was the problem. It's still a problem, at least for me. I don't use spread mode so I'm not affected by it. But just so you know. :)

**Pull request merged**
