### PR TITLE
Remove components/texmagician.ts

### LINKED ISSUE #2753: Insert magic root issue
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

If the main file of an document has the same name or partial the same name as a folder with a imported file the magic root replaces parts of the filename.

### To Reproduce

1. Create a new folder
2. Add a file (e.g. Foldername.tex)
3. Add a folder with partial or full same name (e.g. Foldername)
4. Add a file in the new created folder (e.g. file.tex)
5. Run command insert magic root comment
6. Look at the inserted path (with the example above "% !TeX root = .//.tex")

### Expected behavior

The Path should be:
% !TeX root = ./../Foldername.tex

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
[14:31:12] Initializing LaTeX Workshop.
[14:31:12] Extension root: c:\Users\si5wi6\.vscode\extensions\james-yu.latex-workshop-8.19.2
[14:31:12] $PATH: C:\Program Files\ImageMagick-7.0.11-Q16-HDRI;C:\Python39\Scripts\;C:\Python39\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin;C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin;C:\Python38\Scripts\;C:\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\si5wi6\AppData\Roaming\npm;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\dotnet\;C:\Program Files\Puppet Labs\Puppet\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\PDFtk\bin\;C:\Users\si5wi6\.windows-build-tools\python27\;C:\Users\si5wi6\.cargo\bin;C:\Users\si5wi6\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\si5wi6\AppData\Local\Programs\Python\Python38-32\;C:\Users\si5wi6\AppData\Local\Microsoft\WindowsApps;;C:\Users\si5wi6\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\si5wi6\AppData\Roaming\npm;C:\Users\si5wi6\.dotnet\tools;C:\Users\si5wi6\AppData\Local\Microsoft\WindowsApps;C:\Users\si5wi6\.dotnet\tools;C:\Users\si5wi6\AppData\Local\Pandoc\
[14:31:12] $SHELL: undefined
[14:31:12] latex-workshop.intellisense.update.aggressive.enabled: false
[14:31:12] latex-workshop.intellisense.update.delay: 1000
[14:31:12] latex-workshop.latex.autoBuild.run: "onFileChange"
[14:31:12] latex-workshop.latex.outDir: "%DIR%"
[14:31:12] latex-workshop.latex.recipes: [{"name":"latexmk 🔃","tools":["latexmk"]},{"name":"latexmk (latexmkrc)","tools":["latexmk_rconly"]},{"name":"latexmk (lualatex)","tools":["lualatexmk"]},{"name":"pdflatex ➞ bibtex ➞ pdflatex × 2","tools":["pdflatex","bibtex","pdflatex","pdflatex"]},{"name":"Compile Rnw files","tools":["rnw2tex","latexmk"]},{"name":"Compile Jnw files","tools":["jnw2tex","latexmk"]},{"name":"tectonic","tools":["tectonic"]}]
[14:31:12] latex-workshop.latex.tools: [{"name":"latexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=%OUTDIR%","%DOC%"],"env":{}},{"name":"lualatexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-lualatex","-outdir=%OUTDIR%","%DOC%"],"env":{}},{"name":"latexmk_rconly","command":"latexmk","args":["%DOC%"],"env":{}},{"name":"pdflatex","command":"pdflatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOC%"],"env":{}},{"name":"bibtex","command":"bibtex","args":["%DOCFILE%"],"env":{}},{"name":"rnw2tex","command":"Rscript","args":["-e","knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"],"env":{}},{"name":"jnw2tex","command":"julia","args":["-e","using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"],"env":{}},{"name":"jnw2texmintex","command":"julia","args":["-e","using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"],"env":{}},{"name":"tectonic","command":"tectonic","args":["--synctex","--keep-logs","%DOC%.tex"],"env":{}}]
[14:31:12] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[14:31:12] Creating a new file watcher.
[14:31:12] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[14:31:12] Creating PDF file watcher.
[14:31:12] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[14:31:12] Creating Bib file watcher.
[14:31:12] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[14:31:12] pdflatex is provided by MiKTeX
[14:31:12] [Server] Creating LaTeX Workshop http and websocket server.
[14:31:12] LaTeX Workshop initialized.
[14:31:12] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[14:31:12] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[14:31:12] Current workspace folders: ["file:///c:/Users/si5wi6/Documents/LatexTest"]
[14:31:12] Current workspaceRootDir: file:///c:/Users/si5wi6/Documents/LatexTest
[14:31:12] Found root file by magic comment: c:\Users\si5wi6\Documents\LatexTest\main\Foldername.tex
[14:31:12] Root file changed: from undefined to c:\Users\si5wi6\Documents\LatexTest\main\Foldername.tex
[14:31:12] Start to find all dependencies.
[14:31:12] Root file languageId: latex
[14:31:13] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":49603}
[14:31:13] Reset file watcher.
[14:31:13] Parsing a file and its subfiles: c:\Users\si5wi6\Documents\LatexTest\main\Foldername.tex
[14:31:13] Added to file watcher: c:\Users\si5wi6\Documents\LatexTest\main\Foldername.tex
[14:31:13] Snippet data loaded.
[14:31:15] Manager.fileWatcher.getWatched: {"c:\\Users\\si5wi6\\Documents\\LatexTest\\main":["Foldername.tex"]}
[14:31:15] Manager.filesWatched: ["c:\\Users\\si5wi6\\Documents\\LatexTest\\main\\Foldername.tex"]
[14:31:23] Current workspace folders: ["file:///c:/Users/si5wi6/Documents/LatexTest"]
[14:31:23] Current workspaceRootDir: file:///c:/Users/si5wi6/Documents/LatexTest
[14:31:24] Cannot find fls file: c:\Users\si5wi6\Documents\LatexTest\main\Foldername.fls
[14:31:24] Cannot find fls file: c:\Users\si5wi6\Documents\LatexTest\main\Foldername\file.fls
[14:31:31] ADDTEXROOT command invoked.

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
No new errors while excecuting the steps above
```

## Screenshots

Run Insert magic root in file:
image

The inserted magic root:
image

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.56.2 and 1.57.0-insider
 - Extension version: 8.19.2
 - TeX distribution version: MiKTeX 21.3

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

It's also possible to extend this issue with two folders:
image

leads to the path:
image

### PR DESCRIPTION
**Pull request by tamuratak**
Remove `components/texmagician.ts`. Close #2753.

I am positive about adding features for magic comments. However, the current implementation increases the maintenance burden.

### CODE REVIEW

**Comment by jlelong** [comment]
As this feature does not really interfere with the rest of the extension, I would tempted to just remove https://github.com/James-Yu/LaTeX-Workshop/blob/86f26a7a9f5cb0e0fe63654d44e6f3d6d5e7764f/src/components/texmagician.ts#L20-L36

and use 

```ts
const relativePath = path.relative(path.dirname(editor.document.fileName), val.filePath)
```

instead. It seems that the rest of `TeXMagician` is not that much a big deal.

**Comment by tamuratak** [comment]
>  this feature does not really interfere with the rest of the extension

It is not the point. I am saying that I don't want to support users on this feature. Since the feature is not essential and the code is not easy to maintain.

**Comment by tamuratak** [comment]
I want to clarify that I maintain the extension because maintaining the code is fun, not because maintaining it for users is fun or invaluable. Generally speaking, `maintain for users` is unhealthy for maintainers' mental health.

If we have a part of the code we don't want to maintain, we had better remove it, making the project sustainable in the long run.

**Comment by jlelong** [comment]
I perfectly agree we must find some fun somewhere otherwise we will eventually stop spending a lot of our free time working on the extension. We should probably be more concerned with maintainability when integrating new features, especially when they are essential.

- From my point of view, `texmagician` is not a big deal. Once `getRelativePath` is removed, the rest of the code is quite simple. Although the feature is not essential, I am in favour of trying `path.relative` instead and if that does not solve the issue then I will drop the feature. I will make the change.
- Concerning `toggleSelectedKeyword` things are more complicated. I find the toggle feature quite useful but the current code of `toggleSelectedKeyword` is simple not maintainable. I suggest to leave it as it is for now and I will work on a complete refactoring when I have time.

Are you fine with this?

**Comment by tamuratak** [comment]
I agree.

**Pull request closed without merging**
