### PR TITLE
Deactivate autoclosing for snippet prefixes

### LINKED ISSUE #1423: Some Predefined snippets are incomplete
**Describe the bug [Required]**
The snippet **@(** is incomplete. If you open the latex.json file you can see that the snippet is written as follows

	"(": {
		"prefix": "@(",
		"body": "\\left( $1 \\right",
		"description": "Insert left( ... right)"
	}
It's clear that we are missing **)** after right in the body of the snippet.

*To Reproduce**
1. open any .tex file
2. write the prefix **@(**
3. you will get \left(   \right

**Expected behavior**
The expected behavior is to get \left(   \right)

**Suggestion**
The snippet should be something like this

	"(": {
		"prefix": "@(",
		"body": "\\left( $1 \\right)$0",
		"description": "Insert left( ... right)"
	}
I added the missing **)** and **$0** as a final position for the cursor.

**Note**
**@{** and **@[** are broken in the same way.

**Desktop [Required]:**
 - OS: MacOS Mojave
 - VS Code version: 1.35
 - Extension version: 7.0.0

### LINKED ISSUE #2368: Snippet @{ does not work in some cases. } is missing.
The snippet `@{` does not work in some cases. `}` at the end is missing.  

I encounter this issue when the cursor is at a non-space character.

Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Nov-10-2020 13-05-07

### PR DESCRIPTION
**Pull request by jlelong**
Close #2368.
This should also fix #1423 and #1820

@tamuratak Can you test this ?

### CODE REVIEW

**Comment by tamuratak** [comment]
`\` before `}` is missing in `\right}`

スクリーンショット 2020-11-11 8 37 52

The following change fixes it. I don't know why. Do you know anything about the behavior?

```diff
diff --git a/snippets/latex.json b/snippets/latex.json
index 72f05bc7..8110fc8b 100644
--- a/snippets/latex.json
+++ b/snippets/latex.json
@@ -507,7 +507,7 @@
        },
        "{": {
                "prefix": "@{",
-               "body": "\\left\\{ $1\\right\\}",
+               "body": "\\left\\{ $1\\right\\\\}",
                "description": "left{ ... right}"
        },
        "[": {
```

**Comment by trevorgunn** [comment]
That is really bizarre.

While we're at it, there should be a space after `$1`.

**Comment by jlelong** [comment]
The bizarre `{` escaping is discussed in microsoft/vscode/issues/33933 and microsoft/vscode/issues/32020..

**Comment by tamuratak** [comment]
It works well. Thank you.

**Pull request merged**
