### PR TITLE
Zz/bringmybracketback

### PR DESCRIPTION
**Pull request by innerlee**
Fix https://github.com/James-Yu/LaTeX-Workshop/issues/854
Also re-fix https://github.com/James-Yu/LaTeX-Workshop/issues/609

### CODE REVIEW

**Comment by jlelong** [comment]
This breaks [snippet nesting](https://github.com/James-Yu/LaTeX-Workshop/issues/609#issuecomment-387475664), which was the main issue about snippets and using `${1}`.

Without your PR: `\(@a\)` expands to `\(\alpha\)`.
With it: `\(@a\)` does not expand. `TAB` just jumps out of the `\(...\)`.

**Comment by tecosaur** [comment]
Do you know if there might be any way to force vs code to expand a snippet if it can, then only if it can't move on to the next $ region.

**Comment by jlelong** [comment]
Indeed, I have search a lot for this and never found anything interesting. So I guess it a no.

**Comment by innerlee** [comment]
I do not understand the concept of `nesting`.

For the link https://github.com/James-Yu/LaTeX-Workshop/issues/609#issuecomment-387475664, we can auto complete brackets in math mode with this pr, so no need to type `__<tab>`-like things.

For the `@a` example, I cannot make it work on my machine. Do I need to turn on any option to get the `@something` nesting?

**Comment by innerlee** [comment]
Cannot get it working with the version on marketplace

abc

**Comment by jlelong** [comment]
Have checked that you have `"editor.tabCompletion": true`?

**Comment by innerlee** [comment]
Both `true` or `false` do not work.
latexworkshop version 5.11.1
vscode version 1.27.2
win10

**Comment by jlelong** [comment]
Have you tried playing a bit with `"editor.wordBasedSuggestions": false/true` and `"editor.quickSuggestions": false/true`?
A few people have already reported this but we have never managed to understand what was happening. Maybe this time...

**Comment by Astrantia** [comment]
@jlelong i'll jump in. having both quicksuggestions and wordBasedSuggestions set to true, I still don't get any suggestions when I type `@a`

**Comment by jlelong** [comment]
As @Astrantia pointed out, the completion list for `\a` is so huge, `\alpha` is only on 18th position and you have to type `\al` to have it on the first completion screen. The `@` snippets are designed such that two prefixes cannot start with a common substring. Moreover, `\` requires more keystrokes (3 on my layout) than `@` on many keyboard layouts.

**Comment by Astrantia** [comment]
@jlelong Why does this happen though?
https://i.imgur.com/JhXLMHY.gifv

**Comment by jlelong** [comment]
This is related to [vscode#35651](https://github.com/Microsoft/vscode/issues/35651)
Intellisense does not take into account non alphabetical characters, hence the long list you get. But, no matter the list, the snippet you expect is always the first one!

**Comment by Astrantia** [comment]
@jlelong You misunderstood the point of the gif. I expect to get suggestions for `@8`, `@/`, `@%` as they are also defined

**Comment by Astrantia** [comment]
@jlelong https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json#L42
Notice that it doesn't appear in my gif.

**Comment by Astrantia** [comment]
Update: I had to set `"editor.tabCompletion": "onlySnippets"` for `@%` + Tab to expand the snippet. I still don't get suggestion pop-up, but tabbing works now.

**Comment by innerlee** [comment]
okay, I will wait for https://github.com/Microsoft/vscode/issues/45385

**Pull request closed without merging**
