### PR TITLE
Live reformatter

### LINKED ISSUE #1515: MathReplacement: new feature
Hello,

I've recently been inspired by https://castel.dev/post/lecture-notes-1/ to try to implement some of these features in vscode. However unfortunately
 - vscode does not support regex as snippet prefixes
 - vscode does not support no-prompt auto-activating snippets
 - vscode does not support getting textmate scope

So, I have tried to get this to work. I'd like to know whether you would like this to be incorporated into this extension as a PR, and if you have any thoughts on this in general.

### Feature Preview

feature demo

#### Upside
It 'just happens'
(Can make typing out expressions significantly faster)
#### Downside
It 'just happens'
(has the potential to be annoying)
#### Other important components
_Will_ have:
 - Editable snippets
 - Enable/disable toggle

I've done some work, and created the following two classes:

### TypeFinder
 - Parses backwards from a given position
 - Does this until it can determine whether that position is in math/text mode
 - Seems to take 0-5ms on my machine.

### CompletionWatcher
 - Adds handler to `vscode.workspace.onDidChangeTextDocument`
 - Matches regex snippets against current line up to change
 - When there's a match, the placeholder is removed, and the body is used as a snippet
 - Only active when `typeFinder` says the current env is `maths`

To give a slightly better idea of what I have going on here are some screenshots:

image
image

Also @Astrantia I have a suspicion you may be interested in this given the issue you created in vscode's repo.

### PR DESCRIPTION
**Pull request by tecosaur**
This closes #1515 

live-snippet-demo

## Feature Overview
 - Adds regex based, snipping with the option to auto-activate
 - Snippets come from user configurable json file
 - Can also specify maths/text mode

### Example of auto-activating snippet, `axxb=c`
live-snippet-demo-aa

### Example of user-contributed, non-autoactivating snippet
```json
    {
        "prefix": "([A-Za-z])([A-Za-z])m([A-Za-z])$",
        "body": "$1_{$2 - $3}",
        "mode": "maths"
    },
```
image

### Rough structure of main bits

image

### CODE REVIEW

**Comment by trevorgunn** [comment]
I don't think enabling this by default *and* having pre-defined rules is a good idea.

**Comment by tecosaur** [comment]
Now that I give that a second of thought … yea. I think it's nice to have defaults though so I'll just change the setting to disabled by default.

**Comment by tecosaur** [comment]
@tamuratak if you end up doing a code review (as seems likely), if you could have a close look at the logical structure of `typeFinder` I'd appreciate it. I'm 90% sure that it's fine, but a fresh pair of eyes may notice something I haven't.

**Comment by tamuratak** [comment]
I not interested in this feature.

**Comment by tecosaur** [comment]
@Astrantia would you be interested in doing a code review?

**Comment by jlelong** [comment]
I am not interested in this feature either. I am always concerned by maintainability vs the benefits for how many users. Moreover, I will mostly be away from my keyboard in the coming weeks.

**Comment by tamuratak** [comment]
@tecosaur It looks like there is no need to integrate this PR into LaTeX Workshop because it does not use the API of LaTeX Workshop. This feature can be provided as an independent extension of VS Code. I recommend you to create your own extension for this feature.

**Comment by tecosaur** [comment]
With this and the image pasting, that option is beginning to look more likely, however, with the response to #1515 it does appear that the users of this extension are interested in this feature (ranking by :+1: reactions of the open issues it's currently 3rd/21 and of all time it's 10th/1160).

**Comment by tamuratak** [comment]
I do not think so.

**Comment by tecosaur** [comment]
I'm note sure I understand what you mean by that reply.

**Comment by tecosaur** [comment]
@James-Yu do you plan on going over this at any point in the near future?

**Comment by James-Yu** [comment]
As usual, I am again the like-this-feature guy. Yet the maintainability issue is indeed significant, especially when the feature looks quite isolated to the code structure of this extension.

Nonetheless, I recently come up with an idea of creating a new extension with a name like `LaTeX Utilities` as a complement of LaTeX Workshop. That one may use some API exposed by this one, but provides quite modularized features related to LaTeX. If it may happen, new experimental and fancy-but-advantagous things can find a place to live in.

The reason of not integrating too many things here is that actually the features provided here is highly integrated. By integrated I mean they are interacting with each other in a typical workflow. We made several mistakes of violating this principle in the history (e.g., word count). But we may sort things better with a possible new extension, and let this extension to serve the sole purpose of LaTeX basics (compile, preview, synctex).

I would like to hear from you guys no matter if you are interested in the new thing or not.

**Comment by tecosaur** [comment]
I am very much a fan of that idea, particularly as this is something that (for me) would happen sooner or later, in fact I was planning on releasing an extension in the next few days if nothing happened with this.
> _(me a few comments ago)_ With this and the image pasting, [creating my own extension] is beginning to look more likely

Having two extensions could provide some nice logical seperation
 - LaTeX Workshop; gives you all the basics to get started with LaTeX in vscode without too much hassle
 - LaTeX Untilities; all collection fancy ease-of-life features that the majority of users may not use, but a siginficant number of people will be very interested in

I'm happy to continue with my plan and release an extension like that, but I definately think it makes more sense to have it produced by the same author. If you do end up creating the "LaTeX Utilities" extension I would be very interested in being a maintainer.

**Comment by jlelong** [comment]
LaTeX-Workshop has grown up a lot and already most features a LaTeX could expect from its editor. We should focus on features around compiling, viewing (including `synctex` and preview), and intellisense (all types of completion + snippets + basic manipulations). I vote for developing a new extension (although I may not have much time to devote to it) to include anything going beyond that.

**Comment by James-Yu** [comment]
I will work on that in the following days (hopefully by the weekend). In the meantime, I have some clean-up ideas about LaTeX Workshop, specifically the underlying language parsing part. I will open a new issue to discuss that. @tecosaur I will be more than happy if you could contribute to the upcoming new thing! I am also absolutely fine if you would create one by you 💯

**Comment by tecosaur** [comment]
Ok. I'll get started on `LaTeX Utilities` then (Since uni semester has started I'm desperate for the time savings this PR + image pasting will give me [every few seconds count when taking notes live] ).
@James-Yu @jlelong @tamuratak let me know which of you want to be added as maintainers.

Some time this weekend / next week I'll change the image pasting PR to be adding an adaptor to the new extension.

**Comment by tecosaur** [comment]
Done. https://github.com/tecosaur/LaTeX-Utilities now exists.

**Pull request closed without merging**
