### PR TITLE
Refactor EnvPair module

### PR DESCRIPTION
**Pull request by jlelong**
This PR completely rewrites the `EnvPair` module. We get rid of the old regex logic and use the `latexParser` to build an AST `CommandPair` of all the pairs in the current file.

- It solves #3645 by taking into account pairs of commands in addition to `\begin`/ `end`, inline math and display math
- It solves #3744 
   - _LaTeX Workshop: Select the current environment content_ selects only the inner content of the current environment
   - _LaTeX Workshop: Select the current environment_ selects the whole of the current environment (content + begin / end statements)

Because the current editor may be dirty, it is not easy to cache the AST computed by `parserLatex`. I am still wondering if there is something to be really gained from trying to reuse the AST computed in `buildLaTeXSectionFromFile` for the structure view.

https://github.com/James-Yu/LaTeX-Workshop/blob/f1161d1c0e5f27d258073cfe6f37043ea28007c1/src/providers/structurelib/latex.ts#L86 

Things yet to be done
- [x] Add some tests
- [x] Handle pairs like `\if`/ `\else`, `\if` / `\fi` and `\else` / `\fi` to allow cycling between `\if`, `\else` and `\fi`.

### CODE REVIEW

**Comment by jlelong** [comment]
@James-Yu As you redesigned the tests, may I ask there is an easy way of running a single `.test.ts` file in VS Code debug mode without locally modifying the glob statement in`test/suites/index.ts`?

**Comment by James-Yu** [comment]
@jlelong in the launch.json file, there is a LATEXWORKSHOP_SUITE constant. You can insert the test suite file name (or part of it e.g. 04) to just run tests in the file. For a single test, you may change the test.run function to test.only

**Comment by jlelong** [comment]
Thanks a lot for your explanation. I am just realising that this was explained in the test README. RTFM. My bad!

**Comment by James-Yu** [comment]
Will look into this and the issue backlog in a few days. Extremely busy in the past weeks irl 😫

**Comment by James-Yu** [comment]
The PR looks good to me. (p.s. I'm back!)

**Review by James-Yu — APPROVED** [review]

**Pull request merged**
