### PR TITLE
Use spawnSync to prevent code injection

### LINKED ISSUE #2544: Using execSync is vulnerable
Using `execSync` is vulnerable.

See https://twitter.com/CaptnBanana/status/1365424583898185729

I recommend deleting the feature.

https://github.com/James-Yu/LaTeX-Workshop/blob/50df7f8f4460629c0910e3e7b9e1efca27c5a5a0/src/providers/completer/input.ts#L22-L46

### PR DESCRIPTION
**Pull request by jlelong**
Close #2544

### CODE REVIEW

**Comment by tamuratak** [comment]
How about deleting the feature? Although it is not essential for LaTeX Workshop, the maintenance burden is too much.

**Comment by jlelong** [comment]
I would like to give it one more try. If it creates troubles again, then I will remove it.

**Comment by tamuratak** [comment]
> I would like to give it one more try. If it creates troubles again, then I will remove it.

I see.

Please open a new issue for a new release after you close #2535. It is also OK that a new release before #2535 closed.

**Comment by jlelong** [comment]
#2535 should be closed by the end of the end, a PR is already in progress. I will ask for a new release when it is merged.

**Pull request merged**
